/*
 * Traductions anglaises de la Carte du Talent, indexées par le texte français (sans espaces insécables).
 * Une entrée manquante laisse le texte en français (voir js/i18n.js ; un test vérifie qu'il n'en manque pas).
 */
(function (CT) {
  'use strict';

  CT.EN = {
    " : ": ": ",
    " et ": " and ",
    ", ": ", ",
    "30 derniers jours": "Last 30 days",
    "<strong>{moments} de flow</strong> ces 30 derniers jours, sur <strong>{competences}</strong>.": "<strong>{moments} of flow</strong> in the last 30 days, across <strong>{competences}</strong>.",
    "<strong>{moments} de flow</strong> depuis le début, sur <strong>{competences}</strong>.": "<strong>{moments} of flow</strong> since the start, across <strong>{competences}</strong>.",
    "<strong>{n} moments de flow ici.</strong> Ce territoire te semble-t-il conquis ?": "<strong>{n} flow moments here.</strong> Does this territory feel conquered to you?",
    "<strong>{recents}</strong> sur les 30 derniers jours · {total} au total": "<strong>{recents}</strong> in the last 30 days · {total} in total",
    "Accueil et ouverture": "Welcome and openness",
    "Accueillir": "Welcoming",
    "Acrobatie": "Acrobatics",
    "Administratif": "Admin",
    "Affichage de la carte": "Map display",
    "afin de {texte}": "in order to {texte}",
    "Agréable": "Pleasant",
    "Ajouter": "Add",
    "Ajouter « {nom} » à ma carte": "Add “{nom}” to my map",
    "Ajouter à mes territoires à conquérir": "Add to my territories to conquer",
    "Ajouté": "Added",
    "Allemand": "German",
    "Analyse de données": "Data analysis",
    "Anglais": "English",
    "Animation": "Facilitation",
    "Animation de soirée": "Hosting evenings",
    "Animer": "Facilitating",
    "Animer en visio": "Facilitating online",
    "Animer un atelier": "Running a workshop",
    "Annuler": "Cancel",
    "appris": "learnt",
    "Après {moments} de flow, l'appli te propose de passer la frontière en territoire conquis (seuil réglable dans les Réglages).": "After {moments} of flow, the app suggests turning the frontier into conquered territory (threshold adjustable in Settings).",
    "Arts martiaux": "Martial arts",
    "Associer un objectif à une frontière": "Link a goal to a frontier",
    "Astuce : maintiens appuyé un hexagone pour le déplacer.": "Tip: press and hold a hexagon to move it.",
    "Au-delà de {nom}": "Beyond {nom}",
    "Aucun moment de flow enregistré ici pour l'instant.": "No flow moments recorded here yet.",
    "Aucun objectif pour l'instant. Tu peux en associer un à une frontière.": "No goals yet. You can link one to a frontier.",
    "Aucune honte à ça : ce sont des tâches que tu peux confier à d'autres. Elles iront dans une zone à part.": "No shame in that: these are tasks you can hand over to others. They will go in a separate zone.",
    "Aucune suggestion écartée pour l'instant.": "No dismissed suggestions yet.",
    "Aucune suggestion écartée.": "No dismissed suggestions.",
    "Automatisation no-code": "No-code automation",
    "Autre statut": "Other status",
    "Avancement": "Progress",
    "Beaucoup de défi pour ta maîtrise actuelle : un terrain où tu grandis.": "Lots of challenge for your current skill: ground where you're growing.",
    "Bienvenue sur ta Carte du Talent": "Welcome to your Talent Map",
    "Bravo ! {nom} rejoint tes territoires conquis.": "Well done! {nom} joins your conquered territories.",
    "Brouillard": "Fog",
    "Brouillard : territoire inexploré": "Fog: unexplored territory",
    "Brouillard activé : les territoires inexplorés sont sous les nuages.": "Fog on: unexplored territories are under the clouds.",
    "Brouillard de guerre": "Fog of war",
    "Brouillard désactivé : toute ta carte est visible.": "Fog off: your whole map is visible.",
    "Business": "Business",
    "C'est dans <strong>{nom}</strong> que le flow revient le plus souvent.": "<strong>{nom}</strong> is where flow comes back most often.",
    "Cache les territoires à conquérir tant que tu ne les as pas explorés. Touche un nuage pour l'explorer.": "Hides territories to conquer until you've explored them. Tap a cloud to explore it.",
    "Calisthénie": "Calisthenics",
    "Capitale : ton talent": "Capital: your talent",
    "Capitale : {nom}": "Capital: {nom}",
    "Capitale · ton talent": "Capital · your talent",
    "Carte de démonstration restaurée.": "Demo map restored.",
    "Carte du Talent": "Talent Map",
    "Carte du talent : glisse pour te déplacer, molette ou pincement pour zoomer": "Talent map: drag to move around, scroll or pinch to zoom",
    "Carte exportée. Garde ce fichier précieusement.": "Map exported. Keep this file safe.",
    "Carte importée.": "Map imported.",
    "Carte réorganisée.": "Map rearranged.",
    "carte-du-talent": "talent-map",
    "Ce fichier ne ressemble pas à une Carte du Talent.": "This file doesn't look like a Talent Map.",
    "ce mois-ci": "this month",
    "Ce mois-ci": "This month",
    "Ce que tu apprends en ce moment, ou que tu aimerais apprendre. Ce seront tes frontières.": "What you're learning right now, or would like to learn. These will be your frontiers.",
    "Ce que tu marques « Non » ne sera pas mis sur ta carte.": "Whatever you mark “No” won’t go on your map.",
    "Ce qui est hors de ton talent va sur une île.": "Whatever is outside your talent goes on an island.",
    "Ce qui reste ici rejoindra ta première région ; tu pourras l'ajuster sur la carte.": "Whatever's left here will join your first region; you can adjust it on the map.",
    "Ce qui te met dans le flow": "What puts you in flow",
    "Ce territoire te semble-t-il conquis ? C'est toi qui décides.": "Does this territory feel conquered to you? It's your call.",
    "Ces deux choix remplacent ta carte actuelle, après confirmation. Pense à l'exporter avant.": "Both options replace your current map, after confirmation. Remember to export it first.",
    "Ces moments où tu oublies l'heure. Note-les en vrac : tu les rangeras dans tes régions à la fin. Ceux qui sont hors de ton talent deviendront des îles.": "Those moments when you lose track of time. Jot them down as they come: you'll sort them into your regions at the end. Those outside your talent will become islands.",
    "cette semaine": "this week",
    "Cette semaine": "This week",
    "Chanter": "Singing",
    "Chercher une compétence…": "Search for a skill…",
    "Choisis au moins une compétence.": "Pick at least one skill.",
    "Clown": "Clowning",
    "Coacher": "Coaching",
    "Coacher quelqu'un": "Coaching someone",
    "Combien de fois": "How many times",
    "Commencer avec ma Boussole": "Start with my Compass",
    "Communication": "Communication",
    "Communication non violente": "Nonviolent communication",
    "Composition musicale": "Music composition",
    "Comptabilité": "Accounting",
    "compétence": "skill",
    "compétences": "skills",
    "Compétences qui mènent au flow": "Skills that lead to flow",
    "Concevoir un e-learning": "Designing an e-learning course",
    "Conduire ou faire du vélo, c'est utile, mais ça n'élargit pas vraiment ton terrain de jeu. Garde ce qui ouvre de nouvelles possibilités.": "Driving or cycling is useful, but it doesn't really widen your playing field. Keep what opens up new possibilities.",
    "Construire un message impactant": "Crafting an impactful message",
    "Continuer": "Continue",
    "Corps": "Body",
    "Corps et rythme": "Body and rhythm",
    "Course à pied": "Running",
    "Création": "Creation",
    "Création de jeux": "Game design",
    "Créer des dynamiques humaines positives": "Creating positive human dynamics",
    "Créer ma carte": "Create my map",
    "Créer ma carte (parcours guidé)": "Create my map (guided)",
    "Créer un site web": "Building a website",
    "Créer une communauté": "Building a community",
    "Créer une offre": "Creating an offer",
    "Créer une troupe": "Starting a troupe",
    "D'accord, pas encore. La question reviendra après quelques moments de plus.": "OK, not yet. The question will come back after a few more moments.",
    "D'accord, « {nom} » : cette suggestion ne te sera plus proposée.": "OK, “{nom}”: this suggestion won't be offered again.",
    "Dans le prolongement de {nom}": "A natural extension of {nom}",
    "dans un environnement où {texte}": "in an environment where {texte}",
    "Danse": "Dancing",
    "Danser": "Dancing",
    "de flow": "of flow",
    "Depuis le début": "Since the start",
    "Depuis ta Boussole": "From your Compass",
    "Dernière session retirée.": "Last session removed.",
    "dernière étape": "last step",
    "Dernière étape : le regroupement": "Last step: grouping",
    "Des idées proches de ce que tu vis déjà. Prends ce qui te parle, laisse le reste.": "Ideas close to what you already live. Take what speaks to you, leave the rest.",
    "Descendre {nom}": "Move {nom} down",
    "Design graphique (Canva…)": "Graphic design (Canva…)",
    "Design pédagogique": "Instructional design",
    "Diriger une chorale": "Leading a choir",
    "Discussions passionnantes": "Passionate conversations",
    "Distance au talent": "Distance from your talent",
    "Distance au talent de {nom}": "Distance of {nom} from your talent",
    "Dynamiser": "Energising",
    "Défi": "Challenge",
    "Défi et maîtrise": "Challenge and skill",
    "Défi et maîtrise élevés : la zone de flow par excellence.": "High challenge and high skill: the flow zone at its best.",
    "Défi {defi}, maîtrise {maitrise} : {moments}": "Challenge {defi}, skill {maitrise}: {moments}",
    "Défi →": "Challenge →",
    "Dézoomer": "Zoom out",
    "Elle rejoint tes territoires à conquérir. Tu pourras ajuster sa région dans son panneau.": "It joins your territories to conquer. You can adjust its region in its panel.",
    "Elles apparaissent en pointillés dorés sur ta carte, à l'endroit où elles se poseraient.": "They appear as golden dotted outlines on your map, right where they'd land.",
    "En cours": "Current",
    "En haut à droite, défi et maîtrise élevés : la zone de flow. En haut à gauche, un terrain où tu grandis. En bas à droite, des moments fluides et reposants.": "Top right, high challenge and high skill: the flow zone. Top left, ground where you grow. Bottom right, easy and restful moments.",
    "En quelques mots (facultatif)": "In a few words (optional)",
    "Enregistrer": "Save",
    "Enregistrer ce moment": "Save this moment",
    "Entre {a} et {b}": "Between {a} and {b}",
    "Entrepreneuriat": "Entrepreneurship",
    "envie": "wish",
    "Escalade": "Climbing",
    "Espagnol": "Spanish",
    "Est-ce que ça élargit ton domaine d'action ?": "Does it widen your field of action?",
    "Ex. : 2 sessions de prospection": "E.g. 2 prospecting sessions",
    "Ex. : Anglais": "E.g. English",
    "Ex. : Animer un atelier": "E.g. Running a workshop",
    "Ex. : Animer un podcast en direct": "E.g. Hosting a live podcast",
    "Ex. : Comptabilité": "E.g. Accounting",
    "Ex. : Créer des dynamiques humaines positives": "E.g. Creating positive human dynamics",
    "Ex. : la mise en scène des échanges humains": "E.g. staging human exchanges",
    "Ex. : Transmettre": "E.g. Passing it on",
    "Ex. : Vente": "E.g. Sales",
    "Excel": "Excel",
    "Exemples :": "Examples:",
    "Exigeant": "Demanding",
    "Expert": "Expert",
    "Explorer ce territoire": "Explore this territory",
    "Explorer la carte de démonstration": "Explore the demo map",
    "Exporter": "Export",
    "Exporter ma carte": "Export my map",
    "Exporter ma carte (JSON)": "Export my map (JSON)",
    "Facile": "Easy",
    "Facilitation d'ateliers": "Workshop facilitation",
    "Facilitation graphique": "Graphic facilitation",
    "Faire rire": "Making people laugh",
    "Fermer": "Close",
    "Fichier illisible.": "Unreadable file.",
    "Fil rouge : {texte}": "Common thread: {texte}",
    "Finalement, je le garde": "Actually, I'll keep it",
    "Fixer ses prix": "Setting your prices",
    "flow": "flow",
    "Flow par semaine": "Flow per week",
    "Former des formateurs": "Training trainers",
    "Frontière": "Frontier",
    "Frontière (en cours)": "Frontier (in progress)",
    "Frontières en cours": "Current frontiers",
    "Fédérer": "Bringing people together",
    "Garder ma carte": "Keep my map",
    "Gestion de projet": "Project management",
    "Gestion des conflits": "Conflict management",
    "Gestion du temps": "Time management",
    "Glisse un élément ici": "Drag an item here",
    "Glisse-le dans la région qu'il nourrit. Sur téléphone, touche un élément puis « Poser ici ».": "Drag it into the region it feeds. On a phone, tap an item, then “Drop here”.",
    "Gérer un budget": "Managing a budget",
    "Hors de mon talent : île de flow": "Outside my talent: flow island",
    "Hors région": "Outside any region",
    "Huit régions au maximum.": "Eight regions at most.",
    "IA (LLM)": "AI (LLMs)",
    "IA agentique": "Agentic AI",
    "Importer": "Import",
    "Importer une carte": "Import a map",
    "Importer une carte (JSON)": "Import a map (JSON)",
    "Impossible d'enregistrer dans ce navigateur. Pense à exporter ta carte.": "Can't save in this browser. Remember to export your map.",
    "Improviser": "Improvising",
    "Improviser sur scène": "Improvising on stage",
    "Intelligence émotionnelle": "Emotional intelligence",
    "Intense": "Intense",
    "Intensité": "Intensity",
    "Intensité {n} sur 5": "Intensity {n} out of 5",
    "Italien": "Italian",
    "J'ai fait une session": "I did a session",
    "J'y vais : c'est une frontière": "I'm going for it: it's a frontier",
    "J'étais dans le flow": "I was in flow",
    "J'étais dans le flow ici": "I was in flow here",
    "Je débute": "I'm starting out",
    "Je l'ai conquis": "I've conquered it",
    "Je l'ai déjà conquis": "I've already conquered it",
    "Je le travaille déjà : frontière": "I'm already working on it: frontier",
    "Je le travaille encore": "I'm still working on it",
    "Je tâtonne": "I'm finding my way",
    "Je veux l'apprendre": "I want to learn it",
    "Je…": "I…",
    "Jonglage (bolas)": "Juggling (bolas)",
    "Jongler": "Juggling",
    "Juste bien": "Just right",
    "L'ordre compte : deux régions qui se suivent seront voisines sur ta carte, et la dernière touchera la première. Utilise les flèches pour rapprocher celles qui se ressemblent.": "Order matters: two regions in a row will be neighbours on your map, and the last one will touch the first. Use the arrows to bring similar ones together.",
    "La capitale reste au centre de ta carte.": "The capital stays at the centre of your map.",
    "La mise en scène des échanges humains": "Staging human exchanges",
    "Langue": "Language",
    "Langue des signes": "Sign language",
    "Langues": "Languages",
    "Le fil rouge qui relie tout (facultatif)": "The common thread that ties it all together (optional)",
    "Le remettre à sa place automatique": "Put it back in its automatic place",
    "Leadership": "Leadership",
    "Les 8 dernières semaines, toutes périodes confondues.": "The last 8 weeks, whatever the period selected.",
    "Les grandes facettes de ton talent. Elles deviendront les régions de ta carte. Trois à six, c'est souvent bien.": "The main facets of your talent. They will become the regions of your map. Three to six usually works well.",
    "Les moments de flow notés sur « {nom} » comptent aussi comme des sessions.": "Flow moments noted on “{nom}” also count as sessions.",
    "Les ranger aussi dans ma zone à déléguer": "Also put them in my delegation zone",
    "Les suggestions écartées pourront à nouveau t'être proposées.": "Dismissed suggestions may be offered to you again.",
    "Ludopédagogie": "Game-based learning",
    "lumineux": "bright",
    "Légende": "Legend",
    "Léger": "Light",
    "Maître de cérémonie": "Master of ceremonies",
    "Maîtrise": "Skill",
    "Maîtrise →": "Skill →",
    "Me fixer un objectif": "Set myself a goal",
    "Mentorat": "Mentoring",
    "Mettre en scène": "Staging",
    "Mettre en scène un événement": "Staging an event",
    "Mise en scène": "Staging",
    "Modifier": "Edit",
    "Modéliser le talent de quelqu'un": "Modelling someone's talent",
    "mois": "month",
    "moment": "moment",
    "Moment de flow": "Flow moment",
    "moment de flow": "flow moment",
    "Moment de flow enregistré : {noms}.": "Flow moment saved: {noms}.",
    "Moment supprimé.": "Moment deleted.",
    "moments": "moments",
    "Moments de flow": "Flow moments",
    "moments de flow": "flow moments",
    "Moments de flow par semaine, sur 8 semaines": "Flow moments per week, over 8 weeks",
    "Moments de flow selon le défi et la maîtrise": "Flow moments by challenge and skill",
    "Mon talent": "My talent",
    "Montage vidéo": "Video editing",
    "Monter {nom}": "Move {nom} up",
    "Musical improvisé": "Improvised musical",
    "Médiation": "Mediation",
    "Méditation": "Meditation",
    "Navigation dans la carte": "Map navigation",
    "Networking": "Networking",
    "Newsletter": "Newsletter",
    "Nom de la compétence": "Skill name",
    "Nombre de moments de flow sur une frontière avant que l'appli te propose de la passer en territoire conquis. C'est toujours toi qui confirmes.": "Number of flow moments on a frontier before the app suggests turning it into conquered territory. You always confirm it yourself.",
    "Non": "No",
    "Note (facultative)": "Note (optional)",
    "Note un moment quand tu te sens pleinement engagé : les graphiques se rempliront au fil des semaines.": "Note a moment when you feel fully engaged: the charts will fill up over the weeks.",
    "Noter des élèves": "Grading students",
    "Numérique": "Digital",
    "Négociation": "Negotiation",
    "Objectif": "Goal",
    "objectif : {texte}": "goal: {texte}",
    "Objectif atteint {quand}": "Goal reached {quand}",
    "Objectif atteint {quand} ({sessions})": "Goal reached {quand} ({sessions})",
    "Objectif enregistré.": "Goal saved.",
    "Objectif supprimé.": "Goal deleted.",
    "Objectifs": "Goals",
    "Organisation": "Organisation",
    "Organiser des événements": "Organising events",
    "Oui": "Yes",
    "Oui, je l'ai conquis": "Yes, I've conquered it",
    "Par": "Per",
    "Par exemple : concevoir le message t'a mis dans le flow, le rédiger beaucoup moins.": "For example: designing the message put you in flow, writing it much less so.",
    "Parler face caméra": "Speaking on camera",
    "Pas besoin que ce soit parfait. Tu pourras y revenir plus tard.": "It doesn't need to be perfect. You can come back to it later.",
    "Pas de frontière en ce moment.": "No frontiers right now.",
    "Pas de moment de flow noté ces 30 derniers jours. Le prochain sera le bienvenu.": "No flow moments noted in the last 30 days. The next one will be most welcome.",
    "Pas encore": "Not yet",
    "Pas encore d'objectif sur cette frontière.": "No goal on this frontier yet.",
    "Pas pour maintenant": "Not for now",
    "Pas pour moi": "Not for me",
    "Pense à l'exporter depuis les Réglages si tu veux la garder.": "Remember to export it from Settings if you want to keep it.",
    "Personal branding": "Personal branding",
    "Peu de défi pour ta maîtrise : un moment fluide et ressourçant.": "Little challenge for your skill: an easy, restorative moment.",
    "Photographie": "Photography",
    "Podcast": "Podcast",
    "Poser ici": "Drop here",
    "Pour chacun, indique si c'est proche de ton talent ou plus éloigné (comme Excel ou une langue).": "For each one, say whether it's close to your talent or further away (like Excel or a language).",
    "Pour commencer : tes frontières": "To start: your frontiers",
    "PowerPoint": "PowerPoint",
    "Prenant": "Absorbing",
    "Presque fini : le filtre": "Almost done: the filter",
    "priorité n°1": "top priority",
    "priorité n°{rang}": "priority #{rang}",
    "Priorité": "Priority",
    "En conquête : n°{rang} sur {total}": "Being conquered: #{rang} of {total}",
    "Plus prioritaire": "Higher priority",
    "Moins prioritaire": "Lower priority",
    "J'y vais : le conquérir": "I'm going: conquer it",
    "{nom} : priorité n°{rang}.": "{nom}: priority #{rang}.",
    "Prise de parole en public": "Public speaking",
    "Proche": "Close",
    "Proche de {noms}": "Close to {noms}",
    "Progrès": "Progress",
    "Progrès et objectifs": "Progress and goals",
    "Prolonge ta province {domaine}": "Extends your {domaine} province",
    "Prolonge ta province éloignée": "Extends your distant province",
    "Proposer à nouveau les suggestions écartées": "Suggest dismissed ideas again",
    "Prospection": "Prospecting",
    "Province": "Province",
    "Province {domaine}": "{domaine} province",
    "Province éloignée": "Distant province",
    "Préparation pédagogique": "Lesson planning",
    "Préparer une formation": "Preparing a training course",
    "prête": "ready",
    "Pédagogie": "Teaching",
    "Période": "Period",
    "Qu'as-tu appris et maîtrises-tu aujourd'hui ?": "What have you learnt and mastered today?",
    "Qu'est-ce qui t'a mis dans le flow ?": "What put you in flow?",
    "Qu'est-ce qui te donne envie, juste à côté ?": "What tempts you, just next door?",
    "Qu'est-ce qui te vide et que tu repousses ?": "What drains you and what do you put off?",
    "Quand ?": "When?",
    "Quel est ton talent ?": "What is your talent?",
    "Quelle force avait ce moment ?": "How strong was this moment?",
    "Quelle partie ? (ex. rédaction)": "Which part? (e.g. writing)",
    "Quelque chose t'attend ici. Explore ce territoire pour découvrir de quoi il s'agit.": "Something is waiting for you here. Explore this territory to find out what it is.",
    "Quelque part au bord de ta carte": "Somewhere at the edge of your map",
    "Quels sont tes moments de flow récents ?": "What are your recent flow moments?",
    "Quels sont tes sous-talents ?": "What are your sub-talents?",
    "question {n}": "question {n}",
    "Question {n} sur 6": "Question {n} of 6",
    "Quitter (ta saisie est gardée)": "Leave (your answers are kept)",
    "Quitter : ta saisie est gardée": "Leave: your answers are kept",
    "Raccourcir": "Shorten",
    "Raccourcis cette phrase en quelques mots ({max} caractères au plus), puis ajoute-la.": "Shorten this sentence to a few words ({max} characters at most), then add it.",
    "Range chaque élément dans sa région": "Sort each item into its region",
    "Rattacher au continent": "Attach to the mainland",
    "rayonnant": "radiant",
    "Recommencer de zéro": "Start from scratch",
    "Recommencer de zéro ? Tes réponses en cours seront effacées.": "Start from scratch? Your current answers will be erased.",
    "Relation": "Relationships",
    "Remplacer ta carte actuelle par celle du fichier « {nom} » ?": "Replace your current map with the one in “{nom}”?",
    "Remplacer ta carte actuelle par cette nouvelle carte ? Exporte-la d'abord si tu veux la garder.": "Replace your current map with this new one? Export it first if you want to keep it.",
    "Repartir d'une autre carte": "Start from another map",
    "Reprendre ma carte ({etape})": "Resume my map ({etape})",
    "Reprendre ma création en cours": "Resume my map in progress",
    "Repères": "Landmarks",
    "Respiration et gestion du stress": "Breathing and stress management",
    "Retirer la dernière": "Remove the last one",
    "Retirer {nom}": "Remove {nom}",
    "Retour": "Back",
    "Revenir à la carte de démonstration": "Go back to the demo map",
    "Revenir à la carte de démonstration ? Ta carte actuelle sera remplacée (exporte-la d'abord si tu veux la garder).": "Go back to the demo map? Your current map will be replaced (export it first if you want to keep it).",
    "Revenir à ma Boussole": "Back to my Compass",
    "Rien pour cette période.": "Nothing for this period.",
    "Rimer": "Rhyming",
    "Récemment": "Recently",
    "Rédaction": "Writing",
    "Région": "Region",
    "Région la plus proche": "Closest region",
    "Région {nom}": "Region: {nom}",
    "Régions": "Regions",
    "Régions qui mènent au flow": "Regions that lead to flow",
    "Réglages": "Settings",
    "Réorganiser automatiquement (garde les hexagones déplacés à la main)": "Rearrange automatically (keeps hexagons you moved by hand)",
    "Réorganiser automatiquement la carte ? Les hexagones que tu as déplacés à la main restent où ils sont.": "Rearrange the map automatically? Hexagons you moved by hand stay where they are.",
    "Réorganiser la carte": "Rearrange the map",
    "Réseaux sociaux": "Social media",
    "Réseaux sociaux / communauté en ligne": "Social media / online community",
    "Révéler les gens": "Revealing people",
    "Sauvegarde": "Backup",
    "Scène": "Stage",
    "Scène et mise en scène": "Stage and staging",
    "Sem. du {date}": "Week of {date}",
    "semaine": "week",
    "session": "session",
    "Session notée.": "Session noted.",
    "sessions": "sessions",
    "Seuil de conquête": "Conquest threshold",
    "Seuil de conquête : {n} moments de flow.": "Conquest threshold: {n} flow moments.",
    "Si ce territoire t'attire, ajoute-le à ta carte. Sinon, laisse-le : il ne te sera plus proposé.": "If this territory appeals to you, add it to your map. If not, leave it: it won't be suggested again.",
    "Six questions suffisent pour la dessiner. Compte une dizaine de minutes.": "Six questions are enough to draw it. Allow about ten minutes.",
    "Slam": "Slam poetry",
    "Solide": "Solid",
    "Sourire": "Smiling",
    "Stand-up": "Stand-up",
    "Statut": "Status",
    "Statuts": "Statuses",
    "Storytelling": "Storytelling",
    "Suggestion": "Suggestion",
    "Suggestion : {nom}": "Suggestion: {nom}",
    "Suggestions": "Suggestions",
    "Suggestions de territoires à conquérir": "Suggested territories to conquer",
    "Supprimer ce moment": "Delete this moment",
    "Supprimer ce moment de flow ?": "Delete this flow moment?",
    "Supprimer ce moment du {date}": "Delete this moment from {date}",
    "Supprimer cet objectif ? Les moments de flow restent sur ta carte.": "Delete this goal? The flow moments stay on your map.",
    "Supprimer l'objectif": "Delete the goal",
    "Ta carte actuelle reste en place tant que tu n'as pas créé la nouvelle.": "Your current map stays in place until you've created the new one.",
    "Ta carte attend ses premiers moments de flow": "Your map is waiting for its first flow moments",
    "Ta carte est enregistrée dans ce navigateur. Exporte-la de temps en temps pour ne jamais la perdre, ou pour la retrouver sur un autre appareil.": "Your map is saved in this browser. Export it from time to time so you never lose it, or to open it on another device.",
    "Ta carte est inchangée.": "Your map is unchanged.",
    "Ta carte montre ton talent comme un territoire : un cœur, des régions, des frontières que tu repousses, des îles où tu te ressources.": "Your map shows your talent as a territory: a heart, regions, frontiers you push back, islands where you recharge.",
    "Ta carte à partir de ta Boussole": "Your map from your Compass",
    "Ta carte, à ta façon": "Your map, your way",
    "Ta saisie est gardée : tu pourras reprendre depuis les Réglages.": "Your answers are kept: you can pick up again from Settings.",
    "Team building": "Team building",
    "Territoire conquis": "Conquered territory",
    "Territoire inexploré": "Unexplored territory",
    "Territoire natal": "Home territory",
    "Territoires à explorer": "Territories to explore",
    "Tes contextes d'échec. Ajoute ce que tu pourrais confier à d'autres.": "Your failure contexts. Add what you could hand over to others.",
    "Tes contextes de réussite. Ajoute ceux qui sont de vrais moments de flow.": "Your success contexts. Add the ones that are real flow moments.",
    "Tes frontières": "Your frontiers",
    "Théâtre d'improvisation": "Improv theatre",
    "Ton Anti-Contexte :": "Your Anti-Context:",
    "Ton idée à toi": "Your own idea",
    "Ton talent": "Your talent",
    "Ton talent et tes contextes vécus sont prêts : la création guidée s'ouvre pré-remplie. Tu ajustes chaque étape, puis tu crées ta carte.": "Your talent and lived contexts are ready: the guided creation opens pre-filled. You adjust each step, then create your map.",
    "Ton Talent Unique, pour t'aider à le dire en une phrase courte.": "Your Unique Talent, to help you put it in one short sentence.",
    "Ton territoire": "Your territory",
    "Total": "Total",
    "Tout est rangé.": "Everything is sorted.",
    "Tout reste dans ce navigateur : rien n'est envoyé.": "Everything stays in this browser: nothing is sent.",
    "Tout reste dans ce navigateur. Tu pourras exporter ta carte à tout moment.": "Everything stays in this browser. You can export your map at any time.",
    "Toute la bibliothèque": "The whole library",
    "Toutes les suggestions": "All suggestions",
    "Transmettre": "Passing it on",
    "Transmission": "Passing it on",
    "Trop long pour un hexagone ({max} caractères au plus) : raccourcis « {texte} ».": "Too long for a hexagon ({max} characters at most): shorten “{texte}”.",
    "Très exigeant": "Very demanding",
    "Très facile": "Very easy",
    "Tu as fait le tour des suggestions pour l'instant. La bibliothèque ci-dessous en garde d'autres.": "You've been through all the suggestions for now. The library below holds more.",
    "Tu as placé cet hexagone à la main.": "You placed this hexagon by hand.",
    "Tu avais commencé une création ({etape}) : commencer avec ta Boussole la remplacera.": "You had started creating a map ({etape}): starting with your Compass will replace it.",
    "Tu découvres {nom} !": "You've discovered {nom}!",
    "Tu peux en écrire plusieurs d'un coup, séparés par des virgules.": "You can write several at once, separated by commas.",
    "Un moment compte une fois par région, même s'il touche plusieurs compétences.": "A moment counts once per region, even if it involves several skills.",
    "Un mot pour t'en souvenir": "A few words to remember it",
    "Un regard pour observer, pas pour juger.": "A way to observe, not to judge.",
    "une lueur": "a faint glow",
    "Une partie de cette activité est à déléguer ?": "Could part of this activity be delegated?",
    "Une phrase qui dit ce que tu fais naturellement, mieux que la plupart des gens, et qui te donne de l'énergie.": "One sentence saying what you do naturally, better than most people, and that gives you energy.",
    "Une phrase trop longue pour un hexagone va dans le champ : raccourcis-la, puis ajoute-la.": "A sentence too long for a hexagon goes into the field: shorten it, then add it.",
    "Une piste à explorer": "A lead worth exploring",
    "Vente": "Sales",
    "Vente : 2 sessions par semaine": "Sales: 2 sessions per week",
    "Visualise ton talent comme un territoire, repère ce qui te met dans le flow et regarde tes compétences s'étendre.": "See your talent as a territory, spot what puts you in flow and watch your skills grow.",
    "Voici la carte de démonstration. Tu pourras créer la tienne depuis les Réglages.": "Here's the demo map. You can create your own from Settings.",
    "Voici ta carte ! Touche un hexagone pour l'ajuster ou le déplacer.": "Here's your map! Tap a hexagon to adjust or move it.",
    "Voir le suivi": "See tracking",
    "Voir toute la carte": "See the whole map",
    "Voix et diction": "Voice and diction",
    "Yoga": "Yoga",
    "Zone de flow": "Flow zone",
    "Zone à déléguer": "Delegation zone",
    "Zoomer": "Zoom in",
    "{a} et {b} ont échangé leur place.": "{a} and {b} have swapped places.",
    "{fait} sur {cible} {quand}": "{fait} of {cible} {quand}",
    "{nom} : {n} session par {periode}": "{nom}: {n} session per {periode}",
    "{nom} : {n} sessions par {periode}": "{nom}: {n} sessions per {periode}",
    "{nom} atteint {n} moments de flow : une proposition t'attend dans Progrès.": "{nom} has reached {n} flow moments: a suggestion is waiting for you in Progress.",
    "{nom} attendra son heure. Il reste visible sur ta carte.": "{nom} will wait for its moment. It stays visible on your map.",
    "{nom} devient une frontière : c'est là que tu grandis.": "{nom} becomes a frontier: that's where you grow.",
    "{nom} devient une frontière de ta carte.": "{nom} becomes a frontier on your map.",
    "{nom} devient une île de flow, hors de ton talent principal.": "{nom} becomes a flow island, outside your main talent.",
    "{nom} fait partie de ton territoire natal.": "{nom} is part of your home territory.",
    "{nom} rejoint la zone à déléguer. Tu peux le confier à d'autres.": "{nom} joins the delegation zone. You can hand it over to others.",
    "{nom} rejoint tes territoires à conquérir.": "{nom} joins your territories to conquer.",
    "{nom} retrouve sa place automatique.": "{nom} is back in its automatic place.",
    "{nom} élargit-il ton domaine d'action ?": "Does {nom} widen your field of action?",
    "{n} / {seuil} moments": "{n} / {seuil} moments",
    "{n} proposition de conquête": "{n} conquest suggestion",
    "{n} propositions de conquête": "{n} conquest suggestions",
    "{n} suggestion écartée ne t'est plus proposée.": "{n} dismissed suggestion is no longer offered to you.",
    "{n} suggestions écartées ne te sont plus proposées.": "{n} dismissed suggestions are no longer offered to you.",
    "{province}, du côté de {region}": "{province}, near {region}",
    "« {nom} »": "“{nom}”",
    "« {nom} » compte {moments} de flow": "“{nom}” has {moments} of flow",
    "À conquérir": "To conquer",
    "À déléguer": "To delegate",
    "À l'aise": "At ease",
    "À quel point c'était exigeant ?": "How demanding was it?",
    "À quel point tu te sentais à l'aise ?": "How at ease did you feel?",
    "À ranger": "To sort",
    "ça brille": "shining",
    "Éclat : flow des 30 derniers jours": "Glow: flow in the last 30 days",
    "Éclat : {niveau}": "Glow: {niveau}",
    "Écouter pour aider": "Listening to help",
    "Écrire des prompts": "Writing prompts",
    "Écrire pour le web": "Writing for the web",
    "Écriture créative": "Creative writing",
    "Écriture de sketchs": "Sketch writing",
    "Édition vidéo": "Video editing",
    "Éloigné": "Distant",
    "Éloignée": "Distant",
    "Énergie et humour": "Energy and humour",
    "Être dynamique": "Being dynamic",
    "Être positif": "Being positive",
    "Être très ouvert": "Being very open",
    "Île": "Island",
    "Île de flow": "Flow island",
    "Île {nom}": "Island: {nom}",
    "Île « {nom} », hors du talent principal": "Island “{nom}”, outside your main talent",
    "Îles de flow": "Flow islands",
    "…afin de…": "…in order to…",
    "…dans un environnement où…": "…in an environment where…",
    "Même idée que « {nom} »": "Same idea as “{nom}”",
    "Même univers que « {nom} » ({domaine})": "Same world as “{nom}” ({domaine})",
    "Proche d'éléments de « {nom} »": "Close to items in “{nom}”",
    "Ne colle à aucune région : une île de flow": "Fits no region: a flow island",
    "Analyse": "Analysis",
    "Nature": "Nature",
    "Technique": "Technical",
    "Ta carte à partir de ton résultat du quiz": "Your map from your quiz result",
    "Ton talent et tes sous-talents sont déjà proposés : la création guidée s'ouvre pré-remplie. Tu modifies tout ce que tu veux, puis tu crées ta carte.": "Your talent and sub-talents are already suggested: the guided creation opens pre-filled. Change anything you like, then create your map.",
    "Commencer avec mon résultat": "Start with my result",
    "Depuis ton résultat du quiz": "From your quiz result",
    "{n} idées pour t'inspirer, par domaine. Touche pour ajouter.": "{n} ideas to inspire you, by area. Tap to add.",
    "Voir moins": "Show fewer",
    "Voir plus ({n} idées de plus)": "Show more ({n} more ideas)",
    "On a déjà rangé chaque élément dans la région la plus proche, avec la raison en petit. Garde ce qui te parle, déplace le reste.": "We have already placed each item in the closest region, with the reason in small print. Keep what feels right, move the rest.",
    "Ce qui ne colle à aucune région devient une île.": "Whatever fits no region becomes an island.",
    "Sport et corps": "Sport and body",
    "Art et scène": "Art and stage",
    "Relationnel": "Relationships",
    "Analyse et réflexion": "Analysis and thinking",
    "Technique et numérique": "Technical and digital",
    "Natation": "Swimming",
    "Vélo": "Cycling",
    "Musculation": "Weight training",
    "Randonnée": "Hiking",
    "Pilates": "Pilates",
    "Sport d'équipe": "Team sport",
    "Coaching sportif": "Sports coaching",
    "Théâtre": "Theater",
    "Magie": "Magic",
    "Guitare": "Guitar",
    "Piano": "Piano",
    "Percussions": "Percussion",
    "DJ et mix": "DJing and mixing",
    "Arts du cirque": "Circus arts",
    "Dessin": "Drawing",
    "Peinture": "Painting",
    "Illustration": "Illustration",
    "Sculpture": "Sculpture",
    "Céramique": "Ceramics",
    "Couture": "Sewing",
    "Cuisine": "Cooking",
    "Pâtisserie": "Baking",
    "Écriture de scénarios": "Screenwriting",
    "Poésie": "Poetry",
    "Écoute active": "Active listening",
    "Empathie": "Empathy",
    "Accompagnement individuel": "One-to-one support",
    "Hospitalité": "Hospitality",
    "Bénévolat": "Volunteering",
    "Travail en équipe": "Teamwork",
    "Donner du feedback": "Giving feedback",
    "Relation client": "Customer relations",
    "Tutorat": "Tutoring",
    "Vulgarisation": "Making things accessible",
    "Enseigner aux enfants": "Teaching children",
    "Concevoir un cours": "Designing a course",
    "Recherche et documentation": "Research and documentation",
    "Synthèse": "Synthesis",
    "Veille": "Monitoring trends",
    "Résolution de problèmes": "Problem solving",
    "Esprit critique": "Critical thinking",
    "Statistiques": "Statistics",
    "Audit et diagnostic": "Audit and diagnosis",
    "Stratégie": "Strategy",
    "Modélisation": "Modeling",
    "Prise de décision": "Decision making",
    "Analyse financière": "Financial analysis",
    "Planification": "Planning",
    "Logistique": "Logistics",
    "Priorisation": "Prioritizing",
    "Optimiser des processus": "Optimizing processes",
    "Recrutement": "Recruiting",
    "Déléguer": "Delegating",
    "Coordination d'équipe": "Team coordination",
    "Jardinage": "Gardening",
    "Permaculture": "Permaculture",
    "Écologie et transition": "Ecology and transition",
    "Observation de la nature": "Nature watching",
    "Apiculture": "Beekeeping",
    "Cueillette et plantes": "Foraging and plants",
    "Éducation à la nature": "Nature education",
    "Bricolage": "DIY",
    "Menuiserie": "Carpentry",
    "Mécanique": "Mechanics",
    "Électronique": "Electronics",
    "Réparation": "Repairing things",
    "Programmation": "Programming",
    "Python": "Python",
    "Excel avancé": "Advanced Excel",
    "Référencement (SEO)": "Search optimization (SEO)",
    "Visualisation de données": "Data visualization",
    "Bases de données": "Databases",
    "IA générative": "Generative AI",
    "Design d'interface (UX)": "Interface design (UX)",
    "Chinois": "Chinese",
    "Arabe": "Arabic",
    "Traduction": "Translation",
    "Marketing": "Marketing",
    "Copywriting": "Copywriting",
    "Publicité en ligne": "Online advertising",
    "Partenariats": "Partnerships",
    "E-commerce": "E-commerce",
    "Pitch et levée de fonds": "Pitching and fundraising",
    "Journalisme": "Journalism",
    "Interviewer": "Interviewing",
    "Rédiger des discours": "Writing speeches",
    "Débat et argumentation": "Debate and argumentation",
    "Escape game": "Escape game",
    "Jeux de société": "Board games",
    "Animer un quiz": "Hosting a quiz",
    "Animation pour enfants": "Entertaining children",
    "Bouger": "Moving",
    "Se dépasser": "Pushing yourself",
    "Entraîner": "Training others",
    "Prendre soin du corps": "Caring for the body",
    "Jouer": "Performing",
    "Émouvoir": "Moving people",
    "Écouter": "Listening",
    "Réconcilier": "Reconciling",
    "Créer": "Creating",
    "Imaginer": "Imagining",
    "Inventer": "Inventing",
    "Embellir": "Beautifying",
    "Faire de ses mains": "Making with your hands",
    "Analyser": "Analyzing",
    "Comprendre": "Understanding",
    "Chercher": "Researching",
    "Simplifier": "Simplifying",
    "Décider": "Deciding",
    "Organiser": "Organizing",
    "Coordonner": "Coordinating",
    "Structurer": "Structuring",
    "Planifier": "Planning",
    "Fiabiliser": "Making reliable",
    "Cultiver": "Growing",
    "Explorer la nature": "Exploring nature",
    "Protéger le vivant": "Protecting nature",
    "Prendre l'air": "Getting outdoors",
    "Observer": "Observing",
    "Bricoler": "Tinkering",
    "Réparer": "Fixing",
    "Automatiser": "Automating",
    "Construire": "Building",
    "Programmer": "Programming",
    "Raconter": "Storytelling",
    "Convaincre": "Persuading",
    "Écrire": "Writing",
    "Parler en public": "Speaking in public",
    "Faire connaître": "Spreading the word",
    "Former": "Training",
    "Accompagner": "Supporting",
    "Vulgariser": "Making accessible",
    "Inspirer": "Inspiring",
    "Courir": "Running",
    "Nager": "Swimming",
    "Faire du vélo": "Cycling",
    "Grimper": "Climbing",
    "Faire du yoga": "Doing yoga",
    "Randonner": "Hiking",
    "Jouer en équipe": "Playing in a team",
    "Jouer de la musique": "Playing music",
    "Faire de la magie": "Doing magic",
    "Jouer la comédie": "Acting",
    "Faire rire un groupe": "Making a group laugh",
    "Écouter quelqu'un": "Listening to someone",
    "Accueillir des gens": "Welcoming people",
    "Aider à débloquer une situation": "Helping unblock a situation",
    "Réconcilier deux personnes": "Reconciling two people",
    "Discuter pendant des heures": "Talking for hours",
    "Rencontrer des inconnus": "Meeting strangers",
    "Dessiner": "Drawing",
    "Peindre": "Painting",
    "Cuisiner": "Cooking",
    "Écrire un texte": "Writing a text",
    "Prendre des photos": "Taking photos",
    "Monter une vidéo": "Editing a video",
    "Composer": "Composing",
    "Coudre ou fabriquer": "Sewing or making things",
    "Imaginer un jeu": "Inventing a game",
    "Résoudre un problème complexe": "Solving a complex problem",
    "Analyser des chiffres": "Analyzing figures",
    "Faire une recherche approfondie": "Doing in-depth research",
    "Faire une synthèse": "Writing a summary",
    "Comprendre un système": "Understanding a system",
    "Monter une stratégie": "Building a strategy",
    "Organiser un événement": "Organizing an event",
    "Planifier un projet": "Planning a project",
    "Mettre de l'ordre": "Tidying up",
    "Coordonner une équipe": "Coordinating a team",
    "Optimiser un process": "Optimizing a process",
    "Préparer un voyage": "Planning a trip",
    "Jardiner": "Gardening",
    "Marcher en forêt": "Walking in the forest",
    "Observer les oiseaux": "Birdwatching",
    "Camper": "Camping",
    "Soigner des plantes": "Looking after plants",
    "Regarder les étoiles": "Stargazing",
    "Réparer un objet": "Repairing an object",
    "Automatiser une tâche": "Automating a task",
    "Construire quelque chose": "Building something",
    "Démonter pour comprendre": "Taking things apart to understand",
    "Prendre la parole en public": "Speaking in public",
    "Raconter une histoire": "Telling a story",
    "Enregistrer un podcast": "Recording a podcast",
    "Rédiger un article": "Writing an article",
    "Débattre": "Debating",
    "Expliquer simplement": "Explaining simply",
    "Former un groupe": "Training a group",
    "Préparer un cours": "Preparing a course",
    "Mentorer quelqu'un": "Mentoring someone",
    "Animer un séminaire": "Running a seminar",
    "Faire découvrir une passion": "Sharing a passion",
    "Chant": "Singing",
    "Improvisation": "Improvisation",
    "Coaching": "Coaching"
  };
})(globalThis.CarteTalent = globalThis.CarteTalent || {});
