/*
 * Traducciones al español de la Carta del Talento, indexadas por el texto francés (sin espacios de no separación).
 * Una entrada que falte deja el texto en francés (véase js/i18n.js; una prueba comprueba que no falte ninguna).
 */
(function (CT) {
  'use strict';

  CT.ES = {
    " : ": ": ",
    " et ": " y ",
    ", ": ", ",
    "30 derniers jours": "Últimos 30 días",
    "<strong>{moments} de flow</strong> ces 30 derniers jours, sur <strong>{competences}</strong>.": "<strong>{moments} de flow</strong> en los últimos 30 días, en <strong>{competences}</strong>.",
    "<strong>{moments} de flow</strong> depuis le début, sur <strong>{competences}</strong>.": "<strong>{moments} de flow</strong> desde el principio, en <strong>{competences}</strong>.",
    "<strong>{n} moments de flow ici.</strong> Ce territoire te semble-t-il conquis ?": "<strong>{n} momentos de flow aquí.</strong> ¿Sientes que este territorio ya está conquistado?",
    "<strong>{recents}</strong> sur les 30 derniers jours · {total} au total": "<strong>{recents}</strong> en los últimos 30 días · {total} en total",
    "Accueil et ouverture": "Acogida y apertura",
    "Accueillir": "Acoger",
    "Acrobatie": "Acrobacia",
    "Administratif": "Administrativo",
    "Affichage de la carte": "Visualización del mapa",
    "afin de {texte}": "para {texte}",
    "Agréable": "Agradable",
    "Ajouter": "Añadir",
    "Ajouter « {nom} » à ma carte": "Añadir «{nom}» a mi mapa",
    "Ajouter à mes territoires à conquérir": "Añadir a mis territorios por conquistar",
    "Ajouté": "Añadido",
    "Allemand": "Alemán",
    "Analyse de données": "Análisis de datos",
    "Anglais": "Inglés",
    "Animation": "Animación",
    "Animation de soirée": "Animación de veladas",
    "Animer": "Dinamizar",
    "Animer en visio": "Dinamizar por videollamada",
    "Animer un atelier": "Dirigir un taller",
    "Annuler": "Cancelar",
    "appris": "aprendido",
    "Après {moments} de flow, l'appli te propose de passer la frontière en territoire conquis (seuil réglable dans les Réglages).": "Tras {moments} de flow, la aplicación te propone convertir la frontera en territorio conquistado (umbral ajustable en los Ajustes).",
    "Arts martiaux": "Artes marciales",
    "Associer un objectif à une frontière": "Asociar un objetivo a una frontera",
    "Astuce : maintiens appuyé un hexagone pour le déplacer.": "Consejo: mantén pulsado un hexágono para moverlo.",
    "Au-delà de {nom}": "Más allá de {nom}",
    "Aucun moment de flow enregistré ici pour l'instant.": "Todavía no hay ningún momento de flow registrado aquí.",
    "Aucun objectif pour l'instant. Tu peux en associer un à une frontière.": "Todavía no hay ningún objetivo. Puedes asociar uno a una frontera.",
    "Aucune honte à ça : ce sont des tâches que tu peux confier à d'autres. Elles iront dans une zone à part.": "No hay de qué avergonzarse: son tareas que puedes confiar a otras personas. Irán a una zona aparte.",
    "Aucune suggestion écartée pour l'instant.": "Todavía no hay ninguna sugerencia descartada.",
    "Aucune suggestion écartée.": "Ninguna sugerencia descartada.",
    "Automatisation no-code": "Automatización no-code",
    "Autre statut": "Otro estado",
    "Avancement": "Progreso",
    "Beaucoup de défi pour ta maîtrise actuelle : un terrain où tu grandis.": "Mucho reto para tu dominio actual: un terreno donde creces.",
    "Bienvenue sur ta Carte du Talent": "Te damos la bienvenida a tu Mapa del Talento",
    "Bravo ! {nom} rejoint tes territoires conquis.": "¡Bravo! {nom} se une a tus territorios conquistados.",
    "Brouillard": "Niebla",
    "Brouillard : territoire inexploré": "Niebla: territorio inexplorado",
    "Brouillard activé : les territoires inexplorés sont sous les nuages.": "Niebla activada: los territorios inexplorados están bajo las nubes.",
    "Brouillard de guerre": "Niebla de guerra",
    "Brouillard désactivé : toute ta carte est visible.": "Niebla desactivada: todo tu mapa está visible.",
    "Business": "Negocios",
    "C'est dans <strong>{nom}</strong> que le flow revient le plus souvent.": "Es en <strong>{nom}</strong> donde el flow vuelve con más frecuencia.",
    "Cache les territoires à conquérir tant que tu ne les as pas explorés. Touche un nuage pour l'explorer.": "Oculta los territorios por conquistar mientras no los hayas explorado. Toca una nube para explorarla.",
    "Calisthénie": "Calistenia",
    "Capitale : ton talent": "Capital: tu talento",
    "Capitale : {nom}": "Capital: {nom}",
    "Capitale · ton talent": "Capital · tu talento",
    "Carte de démonstration restaurée.": "Mapa de demostración restaurado.",
    "Carte du Talent": "Mapa del Talento",
    "Carte du talent : glisse pour te déplacer, molette ou pincement pour zoomer": "Mapa del talento: arrastra para moverte, rueda del ratón o pellizco para ampliar",
    "Carte exportée. Garde ce fichier précieusement.": "Mapa exportado. Guarda este archivo con cuidado.",
    "Carte importée.": "Mapa importado.",
    "Carte réorganisée.": "Mapa reorganizado.",
    "carte-du-talent": "mapa-del-talento",
    "Ce fichier ne ressemble pas à une Carte du Talent.": "Este archivo no parece un Mapa del Talento.",
    "ce mois-ci": "este mes",
    "Ce mois-ci": "Este mes",
    "Ce que tu apprends en ce moment, ou que tu aimerais apprendre. Ce seront tes frontières.": "Lo que estás aprendiendo ahora, o te gustaría aprender. Serán tus fronteras.",
    "Ce que tu marques « Non » ne sera pas mis sur ta carte.": "Lo que marques con «No» no se pondrá en tu mapa.",
    "Ce qui est hors de ton talent va sur une île.": "Lo que queda fuera de tu talento va a una isla.",
    "Ce qui reste ici rejoindra ta première région ; tu pourras l'ajuster sur la carte.": "Lo que se queda aquí se unirá a tu primera región; podrás ajustarlo en el mapa.",
    "Ce qui te met dans le flow": "Lo que te pone en flow",
    "Ce territoire te semble-t-il conquis ? C'est toi qui décides.": "¿Sientes que este territorio ya está conquistado? Lo decides tú.",
    "Ces deux choix remplacent ta carte actuelle, après confirmation. Pense à l'exporter avant.": "Estas dos opciones sustituyen tu mapa actual, tras confirmación. Acuérdate de exportarlo antes.",
    "Ces moments où tu oublies l'heure. Note-les en vrac : tu les rangeras dans tes régions à la fin. Ceux qui sont hors de ton talent deviendront des îles.": "Esos momentos en que pierdes la noción del tiempo. Anótalos sin orden: los colocarás en tus regiones al final. Los que queden fuera de tu talento se convertirán en islas.",
    "cette semaine": "esta semana",
    "Cette semaine": "Esta semana",
    "Chanter": "Cantar",
    "Chercher une compétence…": "Buscar una competencia…",
    "Choisis au moins une compétence.": "Elige al menos una competencia.",
    "Clown": "Payaso",
    "Coacher": "Hacer coaching",
    "Coacher quelqu'un": "Hacer coaching a alguien",
    "Combien de fois": "Cuántas veces",
    "Commencer avec ma Boussole": "Empezar con mi Brújula",
    "Communication": "Comunicación",
    "Communication non violente": "Comunicación no violenta",
    "Composition musicale": "Composición musical",
    "Comptabilité": "Contabilidad",
    "compétence": "competencia",
    "compétences": "competencias",
    "Compétences qui mènent au flow": "Competencias que llevan al flow",
    "Concevoir un e-learning": "Diseñar un e-learning",
    "Conduire ou faire du vélo, c'est utile, mais ça n'élargit pas vraiment ton terrain de jeu. Garde ce qui ouvre de nouvelles possibilités.": "Conducir o ir en bici es útil, pero no amplía de verdad tu terreno de juego. Quédate con lo que abre nuevas posibilidades.",
    "Construire un message impactant": "Construir un mensaje impactante",
    "Continuer": "Continuar",
    "Corps": "Cuerpo",
    "Corps et rythme": "Cuerpo y ritmo",
    "Course à pied": "Correr",
    "Création": "Creación",
    "Création de jeux": "Creación de juegos",
    "Créer des dynamiques humaines positives": "Crear dinámicas humanas positivas",
    "Créer ma carte": "Crear mi mapa",
    "Créer ma carte (parcours guidé)": "Crear mi mapa (recorrido guiado)",
    "Créer un site web": "Crear un sitio web",
    "Créer une communauté": "Crear una comunidad",
    "Créer une offre": "Crear una oferta",
    "Créer une troupe": "Crear una compañía",
    "D'accord, pas encore. La question reviendra après quelques moments de plus.": "De acuerdo, todavía no. La pregunta volverá después de unos momentos más.",
    "D'accord, « {nom} » : cette suggestion ne te sera plus proposée.": "De acuerdo, «{nom}»: esta sugerencia ya no se te propondrá.",
    "Dans le prolongement de {nom}": "En la prolongación de {nom}",
    "dans un environnement où {texte}": "en un entorno donde {texte}",
    "Danse": "Baile",
    "Danser": "Bailar",
    "de flow": "de flow",
    "Depuis le début": "Desde el principio",
    "Depuis ta Boussole": "Desde tu Brújula",
    "Dernière session retirée.": "Última sesión retirada.",
    "dernière étape": "última etapa",
    "Dernière étape : le regroupement": "Última etapa: la agrupación",
    "Des idées proches de ce que tu vis déjà. Prends ce qui te parle, laisse le reste.": "Ideas cercanas a lo que ya vives. Toma lo que te hable y deja el resto.",
    "Descendre {nom}": "Bajar {nom}",
    "Design graphique (Canva…)": "Diseño gráfico (Canva…)",
    "Design pédagogique": "Diseño pedagógico",
    "Diriger une chorale": "Dirigir un coro",
    "Discussions passionnantes": "Conversaciones apasionantes",
    "Distance au talent": "Distancia al talento",
    "Distance au talent de {nom}": "Distancia al talento de {nom}",
    "Dynamiser": "Dar energía",
    "Défi": "Reto",
    "Défi et maîtrise": "Reto y dominio",
    "Défi et maîtrise élevés : la zone de flow par excellence.": "Reto y dominio altos: la zona de flow por excelencia.",
    "Défi {defi}, maîtrise {maitrise} : {moments}": "Reto {defi}, dominio {maitrise}: {moments}",
    "Défi →": "Reto →",
    "Dézoomer": "Alejar",
    "Elle rejoint tes territoires à conquérir. Tu pourras ajuster sa région dans son panneau.": "Se une a tus territorios por conquistar. Podrás ajustar su región en su panel.",
    "Elles apparaissent en pointillés dorés sur ta carte, à l'endroit où elles se poseraient.": "Aparecen punteadas en dorado en tu mapa, en el lugar donde se colocarían.",
    "En cours": "En curso",
    "En haut à droite, défi et maîtrise élevés : la zone de flow. En haut à gauche, un terrain où tu grandis. En bas à droite, des moments fluides et reposants.": "Arriba a la derecha, reto y dominio altos: la zona de flow. Arriba a la izquierda, un terreno donde creces. Abajo a la derecha, momentos fluidos y relajantes.",
    "En quelques mots (facultatif)": "En pocas palabras (opcional)",
    "Enregistrer": "Guardar",
    "Enregistrer ce moment": "Guardar este momento",
    "Entre {a} et {b}": "Entre {a} y {b}",
    "Entrepreneuriat": "Emprendimiento",
    "envie": "deseo",
    "Escalade": "Escalada",
    "Espagnol": "Español",
    "Est-ce que ça élargit ton domaine d'action ?": "¿Esto amplía tu campo de acción?",
    "Ex. : 2 sessions de prospection": "Ej.: 2 sesiones de prospección",
    "Ex. : Anglais": "Ej.: Inglés",
    "Ex. : Animer un atelier": "Ej.: Dirigir un taller",
    "Ex. : Animer un podcast en direct": "Ej.: Dirigir un pódcast en directo",
    "Ex. : Comptabilité": "Ej.: Contabilidad",
    "Ex. : Créer des dynamiques humaines positives": "Ej.: Crear dinámicas humanas positivas",
    "Ex. : la mise en scène des échanges humains": "Ej.: la puesta en escena de los intercambios humanos",
    "Ex. : Transmettre": "Ej.: Transmitir",
    "Ex. : Vente": "Ej.: Ventas",
    "Excel": "Excel",
    "Exemples :": "Ejemplos:",
    "Exigeant": "Exigente",
    "Expert": "Experto",
    "Explorer ce territoire": "Explorar este territorio",
    "Explorer la carte de démonstration": "Explorar el mapa de demostración",
    "Exporter": "Exportar",
    "Exporter ma carte": "Exportar mi mapa",
    "Exporter ma carte (JSON)": "Exportar mi mapa (JSON)",
    "Facile": "Fácil",
    "Facilitation d'ateliers": "Facilitación de talleres",
    "Facilitation graphique": "Facilitación gráfica",
    "Faire rire": "Hacer reír",
    "Fermer": "Cerrar",
    "Fichier illisible.": "Archivo ilegible.",
    "Fil rouge : {texte}": "Hilo conductor: {texte}",
    "Finalement, je le garde": "Al final, me lo quedo",
    "Fixer ses prix": "Fijar tus precios",
    "flow": "flow",
    "Flow par semaine": "Flow por semana",
    "Former des formateurs": "Formar a formadores",
    "Frontière": "Frontera",
    "Frontière (en cours)": "Frontera (en curso)",
    "Frontières en cours": "Fronteras en curso",
    "Fédérer": "Aunar",
    "Garder ma carte": "Conservar mi mapa",
    "Gestion de projet": "Gestión de proyectos",
    "Gestion des conflits": "Gestión de conflictos",
    "Gestion du temps": "Gestión del tiempo",
    "Glisse un élément ici": "Arrastra un elemento aquí",
    "Glisse-le dans la région qu'il nourrit. Sur téléphone, touche un élément puis « Poser ici ».": "Arrástralo a la región que alimenta. En el móvil, toca un elemento y después «Colocar aquí».",
    "Gérer un budget": "Gestionar un presupuesto",
    "Hors de mon talent : île de flow": "Fuera de mi talento: isla de flow",
    "Hors région": "Sin región",
    "Huit régions au maximum.": "Ocho regiones como máximo.",
    "IA (LLM)": "IA (LLM)",
    "IA agentique": "IA agéntica",
    "Importer": "Importar",
    "Importer une carte": "Importar un mapa",
    "Importer une carte (JSON)": "Importar un mapa (JSON)",
    "Impossible d'enregistrer dans ce navigateur. Pense à exporter ta carte.": "No se puede guardar en este navegador. Acuérdate de exportar tu mapa.",
    "Improviser": "Improvisar",
    "Improviser sur scène": "Improvisar en escena",
    "Intelligence émotionnelle": "Inteligencia emocional",
    "Intense": "Intenso",
    "Intensité": "Intensidad",
    "Intensité {n} sur 5": "Intensidad {n} de 5",
    "Italien": "Italiano",
    "J'ai fait une session": "He hecho una sesión",
    "J'y vais : c'est une frontière": "Voy a por ello: es una frontera",
    "J'étais dans le flow": "Estaba en flow",
    "J'étais dans le flow ici": "Estaba en flow aquí",
    "Je débute": "Estoy empezando",
    "Je l'ai conquis": "Lo he conquistado",
    "Je l'ai déjà conquis": "Ya lo he conquistado",
    "Je le travaille déjà : frontière": "Ya lo trabajo: frontera",
    "Je le travaille encore": "Todavía lo trabajo",
    "Je tâtonne": "Voy tanteando",
    "Je veux l'apprendre": "Quiero aprenderlo",
    "Je…": "Yo…",
    "Jonglage (bolas)": "Malabares (boleadoras)",
    "Jongler": "Hacer malabares",
    "Juste bien": "Justo en su punto",
    "L'ordre compte : deux régions qui se suivent seront voisines sur ta carte, et la dernière touchera la première. Utilise les flèches pour rapprocher celles qui se ressemblent.": "El orden cuenta: dos regiones consecutivas serán vecinas en tu mapa, y la última tocará la primera. Usa las flechas para acercar las que se parecen.",
    "La capitale reste au centre de ta carte.": "La capital se queda en el centro de tu mapa.",
    "La mise en scène des échanges humains": "La puesta en escena de los intercambios humanos",
    "Langue": "Idioma",
    "Langue des signes": "Lengua de signos",
    "Langues": "Idiomas",
    "Le fil rouge qui relie tout (facultatif)": "El hilo conductor que lo une todo (opcional)",
    "Le remettre à sa place automatique": "Devolverlo a su sitio automático",
    "Leadership": "Liderazgo",
    "Les 8 dernières semaines, toutes périodes confondues.": "Las últimas 8 semanas, de todos los periodos.",
    "Les grandes facettes de ton talent. Elles deviendront les régions de ta carte. Trois à six, c'est souvent bien.": "Las grandes facetas de tu talento. Se convertirán en las regiones de tu mapa. Entre tres y seis suele ir bien.",
    "Les moments de flow notés sur « {nom} » comptent aussi comme des sessions.": "Los momentos de flow anotados en «{nom}» también cuentan como sesiones.",
    "Les ranger aussi dans ma zone à déléguer": "Colocarlos también en mi zona por delegar",
    "Les suggestions écartées pourront à nouveau t'être proposées.": "Las sugerencias descartadas podrán volver a proponerte.",
    "Ludopédagogie": "Aprendizaje a través del juego",
    "lumineux": "luminoso",
    "Légende": "Leyenda",
    "Léger": "Ligero",
    "Maître de cérémonie": "Maestro de ceremonias",
    "Maîtrise": "Dominio",
    "Maîtrise →": "Dominio →",
    "Me fixer un objectif": "Fijarme un objetivo",
    "Mentorat": "Mentoría",
    "Mettre en scène": "Poner en escena",
    "Mettre en scène un événement": "Poner en escena un evento",
    "Mise en scène": "Puesta en escena",
    "Modifier": "Modificar",
    "Modéliser le talent de quelqu'un": "Modelar el talento de alguien",
    "mois": "mes",
    "moment": "momento",
    "Moment de flow": "Momento de flow",
    "moment de flow": "momento de flow",
    "Moment de flow enregistré : {noms}.": "Momento de flow guardado: {noms}.",
    "Moment supprimé.": "Momento eliminado.",
    "moments": "momentos",
    "Moments de flow": "Momentos de flow",
    "moments de flow": "momentos de flow",
    "Moments de flow par semaine, sur 8 semaines": "Momentos de flow por semana, durante 8 semanas",
    "Moments de flow selon le défi et la maîtrise": "Momentos de flow según el reto y el dominio",
    "Mon talent": "Mi talento",
    "Montage vidéo": "Edición de vídeo",
    "Monter {nom}": "Subir {nom}",
    "Musical improvisé": "Musical improvisado",
    "Médiation": "Mediación",
    "Méditation": "Meditación",
    "Navigation dans la carte": "Navegación por el mapa",
    "Networking": "Networking",
    "Newsletter": "Boletín",
    "Nom de la compétence": "Nombre de la competencia",
    "Nombre de moments de flow sur une frontière avant que l'appli te propose de la passer en territoire conquis. C'est toujours toi qui confirmes.": "Número de momentos de flow en una frontera antes de que la aplicación te proponga pasarla a territorio conquistado. Siempre eres tú quien confirma.",
    "Non": "No",
    "Note (facultative)": "Nota (opcional)",
    "Note un moment quand tu te sens pleinement engagé : les graphiques se rempliront au fil des semaines.": "Anota un momento cuando te sientas plenamente implicado/a: los gráficos se irán llenando con las semanas.",
    "Noter des élèves": "Poner notas a alumnos",
    "Numérique": "Digital",
    "Négociation": "Negociación",
    "Objectif": "Objetivo",
    "objectif : {texte}": "objetivo: {texte}",
    "Objectif atteint {quand}": "Objetivo alcanzado {quand}",
    "Objectif atteint {quand} ({sessions})": "Objetivo alcanzado {quand} ({sessions})",
    "Objectif enregistré.": "Objetivo guardado.",
    "Objectif supprimé.": "Objetivo eliminado.",
    "Objectifs": "Objetivos",
    "Organisation": "Organización",
    "Organiser des événements": "Organizar eventos",
    "Oui": "Sí",
    "Oui, je l'ai conquis": "Sí, lo he conquistado",
    "Par": "Por",
    "Par exemple : concevoir le message t'a mis dans le flow, le rédiger beaucoup moins.": "Por ejemplo: diseñar el mensaje te puso en flow, redactarlo mucho menos.",
    "Parler face caméra": "Hablar ante la cámara",
    "Pas besoin que ce soit parfait. Tu pourras y revenir plus tard.": "No hace falta que sea perfecto. Podrás volver a ello más tarde.",
    "Pas de frontière en ce moment.": "No hay ninguna frontera en este momento.",
    "Pas de moment de flow noté ces 30 derniers jours. Le prochain sera le bienvenu.": "Ningún momento de flow anotado en los últimos 30 días. El próximo será bienvenido.",
    "Pas encore": "Todavía no",
    "Pas encore d'objectif sur cette frontière.": "Todavía no hay ningún objetivo en esta frontera.",
    "Pas pour maintenant": "Ahora no",
    "Pas pour moi": "No es para mí",
    "Pense à l'exporter depuis les Réglages si tu veux la garder.": "Acuérdate de exportarlo desde los Ajustes si quieres conservarlo.",
    "Personal branding": "Marca personal",
    "Peu de défi pour ta maîtrise : un moment fluide et ressourçant.": "Poco reto para tu dominio: un momento fluido y reparador.",
    "Photographie": "Fotografía",
    "Podcast": "Pódcast",
    "Poser ici": "Colocar aquí",
    "Pour chacun, indique si c'est proche de ton talent ou plus éloigné (comme Excel ou une langue).": "Para cada uno, indica si está cerca de tu talento o más lejos (como Excel o un idioma).",
    "Pour commencer : tes frontières": "Para empezar: tus fronteras",
    "PowerPoint": "PowerPoint",
    "Prenant": "Absorbente",
    "Presque fini : le filtre": "Casi terminado: el filtro",
    "priorité n°1": "prioridad n.º 1",
    "priorité n°{rang}": "prioridad n.º {rang}",
    "Priorité": "Prioridad",
    "En conquête : n°{rang} sur {total}": "En conquista: n.º {rang} de {total}",
    "Plus prioritaire": "Más prioritario",
    "Moins prioritaire": "Menos prioritario",
    "J'y vais : le conquérir": "Voy a por ello: conquistarlo",
    "{nom} : priorité n°{rang}.": "{nom}: prioridad n.º {rang}.",
    "Prise de parole en public": "Hablar en público",
    "Proche": "Cercano",
    "Proche de {noms}": "Cerca de {noms}",
    "Progrès": "Progreso",
    "Progrès et objectifs": "Progreso y objetivos",
    "Prolonge ta province {domaine}": "Prolonga tu provincia {domaine}",
    "Prolonge ta province éloignée": "Prolonga tu provincia lejana",
    "Proposer à nouveau les suggestions écartées": "Volver a proponer las sugerencias descartadas",
    "Prospection": "Prospección",
    "Province": "Provincia",
    "Province {domaine}": "Provincia {domaine}",
    "Province éloignée": "Provincia lejana",
    "Préparation pédagogique": "Preparación pedagógica",
    "Préparer une formation": "Preparar una formación",
    "prête": "lista",
    "Pédagogie": "Pedagogía",
    "Période": "Periodo",
    "Qu'as-tu appris et maîtrises-tu aujourd'hui ?": "¿Qué has aprendido y dominas hoy?",
    "Qu'est-ce qui t'a mis dans le flow ?": "¿Qué te ha puesto en flow?",
    "Qu'est-ce qui te donne envie, juste à côté ?": "¿Qué te apetece, justo al lado?",
    "Qu'est-ce qui te vide et que tu repousses ?": "¿Qué te agota y vas aplazando?",
    "Quand ?": "¿Cuándo?",
    "Quel est ton talent ?": "¿Cuál es tu talento?",
    "Quelle force avait ce moment ?": "¿Qué intensidad tuvo este momento?",
    "Quelle partie ? (ex. rédaction)": "¿Qué parte? (p. ej., redacción)",
    "Quelque chose t'attend ici. Explore ce territoire pour découvrir de quoi il s'agit.": "Algo te espera aquí. Explora este territorio para descubrir qué es.",
    "Quelque part au bord de ta carte": "En algún lugar al borde de tu mapa",
    "Quels sont tes moments de flow récents ?": "¿Cuáles son tus momentos de flow recientes?",
    "Quels sont tes sous-talents ?": "¿Cuáles son tus subtalentos?",
    "question {n}": "pregunta {n}",
    "Question {n} sur 6": "Pregunta {n} de 6",
    "Quitter (ta saisie est gardée)": "Salir (lo que has escrito se conserva)",
    "Quitter : ta saisie est gardée": "Salir: lo que has escrito se conserva",
    "Raccourcir": "Acortar",
    "Raccourcis cette phrase en quelques mots ({max} caractères au plus), puis ajoute-la.": "Acorta esta frase a unas pocas palabras (máximo {max} caracteres) y añádela.",
    "Range chaque élément dans sa région": "Coloca cada elemento en su región",
    "Rattacher au continent": "Unir al continente",
    "rayonnant": "radiante",
    "Recommencer de zéro": "Empezar de cero",
    "Recommencer de zéro ? Tes réponses en cours seront effacées.": "¿Empezar de cero? Se borrarán tus respuestas en curso.",
    "Relation": "Relaciones",
    "Remplacer ta carte actuelle par celle du fichier « {nom} » ?": "¿Sustituir tu mapa actual por el del archivo «{nom}»?",
    "Remplacer ta carte actuelle par cette nouvelle carte ? Exporte-la d'abord si tu veux la garder.": "¿Sustituir tu mapa actual por este mapa nuevo? Expórtalo antes si quieres conservarlo.",
    "Repartir d'une autre carte": "Partir de otro mapa",
    "Reprendre ma carte ({etape})": "Retomar mi mapa ({etape})",
    "Reprendre ma création en cours": "Retomar mi creación en curso",
    "Repères": "Referencias",
    "Respiration et gestion du stress": "Respiración y gestión del estrés",
    "Retirer la dernière": "Quitar la última",
    "Retirer {nom}": "Quitar {nom}",
    "Retour": "Volver",
    "Revenir à la carte de démonstration": "Volver al mapa de demostración",
    "Revenir à la carte de démonstration ? Ta carte actuelle sera remplacée (exporte-la d'abord si tu veux la garder).": "¿Volver al mapa de demostración? Tu mapa actual será sustituido (expórtalo antes si quieres conservarlo).",
    "Revenir à ma Boussole": "Volver a mi Brújula",
    "Rien pour cette période.": "Nada para este periodo.",
    "Rimer": "Rimar",
    "Récemment": "Recientemente",
    "Rédaction": "Redacción",
    "Région": "Región",
    "Région la plus proche": "Región más cercana",
    "Région {nom}": "Región {nom}",
    "Régions": "Regiones",
    "Régions qui mènent au flow": "Regiones que llevan al flow",
    "Réglages": "Ajustes",
    "Réorganiser automatiquement (garde les hexagones déplacés à la main)": "Reorganizar automáticamente (conserva los hexágonos movidos a mano)",
    "Réorganiser automatiquement la carte ? Les hexagones que tu as déplacés à la main restent où ils sont.": "¿Reorganizar el mapa automáticamente? Los hexágonos que has movido a mano se quedan donde están.",
    "Réorganiser la carte": "Reorganizar el mapa",
    "Réseaux sociaux": "Redes sociales",
    "Réseaux sociaux / communauté en ligne": "Redes sociales / comunidad en línea",
    "Révéler les gens": "Sacar lo mejor de la gente",
    "Sauvegarde": "Copia de seguridad",
    "Scène": "Escena",
    "Scène et mise en scène": "Escena y puesta en escena",
    "Sem. du {date}": "Sem. del {date}",
    "semaine": "semana",
    "session": "sesión",
    "Session notée.": "Sesión anotada.",
    "sessions": "sesiones",
    "Seuil de conquête": "Umbral de conquista",
    "Seuil de conquête : {n} moments de flow.": "Umbral de conquista: {n} momentos de flow.",
    "Si ce territoire t'attire, ajoute-le à ta carte. Sinon, laisse-le : il ne te sera plus proposé.": "Si este territorio te atrae, añádelo a tu mapa. Si no, déjalo: no se te volverá a proponer.",
    "Six questions suffisent pour la dessiner. Compte une dizaine de minutes.": "Seis preguntas bastan para dibujarlo. Cuenta unos diez minutos.",
    "Slam": "Slam",
    "Solide": "Sólido",
    "Sourire": "Sonreír",
    "Stand-up": "Stand-up",
    "Statut": "Estado",
    "Statuts": "Estados",
    "Storytelling": "Storytelling",
    "Suggestion": "Sugerencia",
    "Suggestion : {nom}": "Sugerencia: {nom}",
    "Suggestions": "Sugerencias",
    "Suggestions de territoires à conquérir": "Sugerencias de territorios por conquistar",
    "Supprimer ce moment": "Eliminar este momento",
    "Supprimer ce moment de flow ?": "¿Eliminar este momento de flow?",
    "Supprimer ce moment du {date}": "Eliminar este momento del {date}",
    "Supprimer cet objectif ? Les moments de flow restent sur ta carte.": "¿Eliminar este objetivo? Los momentos de flow se quedan en tu mapa.",
    "Supprimer l'objectif": "Eliminar el objetivo",
    "Ta carte actuelle reste en place tant que tu n'as pas créé la nouvelle.": "Tu mapa actual se queda como está mientras no hayas creado el nuevo.",
    "Ta carte attend ses premiers moments de flow": "Tu mapa espera sus primeros momentos de flow",
    "Ta carte est enregistrée dans ce navigateur. Exporte-la de temps en temps pour ne jamais la perdre, ou pour la retrouver sur un autre appareil.": "Tu mapa se guarda en este navegador. Expórtalo de vez en cuando para no perderlo nunca, o para recuperarlo en otro dispositivo.",
    "Ta carte est inchangée.": "Tu mapa no ha cambiado.",
    "Ta carte montre ton talent comme un territoire : un cœur, des régions, des frontières que tu repousses, des îles où tu te ressources.": "Tu mapa muestra tu talento como un territorio: un corazón, regiones, fronteras que vas empujando, islas donde recargas energías.",
    "Ta carte à partir de ta Boussole": "Tu mapa a partir de tu Brújula",
    "Ta carte, à ta façon": "Tu mapa, a tu manera",
    "Ta saisie est gardée : tu pourras reprendre depuis les Réglages.": "Lo que has escrito se conserva: podrás retomarlo desde los Ajustes.",
    "Team building": "Team building",
    "Territoire conquis": "Territorio conquistado",
    "Territoire inexploré": "Territorio inexplorado",
    "Territoire natal": "Territorio natal",
    "Territoires à explorer": "Territorios por explorar",
    "Tes contextes d'échec. Ajoute ce que tu pourrais confier à d'autres.": "Tus contextos de fracaso. Añade lo que podrías confiar a otras personas.",
    "Tes contextes de réussite. Ajoute ceux qui sont de vrais moments de flow.": "Tus contextos de éxito. Añade los que son verdaderos momentos de flow.",
    "Tes frontières": "Tus fronteras",
    "Théâtre d'improvisation": "Teatro de improvisación",
    "Ton Anti-Contexte :": "Tu Anti-Contexto:",
    "Ton idée à toi": "Tu propia idea",
    "Ton talent": "Tu talento",
    "Ton talent et tes contextes vécus sont prêts : la création guidée s'ouvre pré-remplie. Tu ajustes chaque étape, puis tu crées ta carte.": "Tu talento y tus contextos vividos están listos: la creación guiada se abre ya rellenada. Ajustas cada etapa y después creas tu mapa.",
    "Ton Talent Unique, pour t'aider à le dire en une phrase courte.": "Tu Talento Único, para ayudarte a decirlo en una frase corta.",
    "Ton territoire": "Tu territorio",
    "Total": "Total",
    "Tout est rangé.": "Todo está colocado.",
    "Tout reste dans ce navigateur : rien n'est envoyé.": "Todo se queda en este navegador: no se envía nada.",
    "Tout reste dans ce navigateur. Tu pourras exporter ta carte à tout moment.": "Todo se queda en este navegador. Podrás exportar tu mapa en cualquier momento.",
    "Toute la bibliothèque": "Toda la biblioteca",
    "Toutes les suggestions": "Todas las sugerencias",
    "Transmettre": "Transmitir",
    "Transmission": "Transmisión",
    "Trop long pour un hexagone ({max} caractères au plus) : raccourcis « {texte} ».": "Demasiado largo para un hexágono (máximo {max} caracteres): acorta «{texte}».",
    "Très exigeant": "Muy exigente",
    "Très facile": "Muy fácil",
    "Tu as fait le tour des suggestions pour l'instant. La bibliothèque ci-dessous en garde d'autres.": "Has repasado todas las sugerencias por ahora. La biblioteca de abajo guarda más.",
    "Tu as placé cet hexagone à la main.": "Has colocado este hexágono a mano.",
    "Tu avais commencé une création ({etape}) : commencer avec ta Boussole la remplacera.": "Habías empezado una creación ({etape}): empezar con tu Brújula la sustituirá.",
    "Tu découvres {nom} !": "¡Estás descubriendo {nom}!",
    "Tu peux en écrire plusieurs d'un coup, séparés par des virgules.": "Puedes escribir varios a la vez, separados por comas.",
    "Un moment compte une fois par région, même s'il touche plusieurs compétences.": "Un momento cuenta una vez por región, aunque afecte a varias competencias.",
    "Un mot pour t'en souvenir": "Una palabra para acordarte",
    "Un regard pour observer, pas pour juger.": "Una mirada para observar, no para juzgar.",
    "une lueur": "un destello",
    "Une partie de cette activité est à déléguer ?": "¿Hay una parte de esta actividad que se pueda delegar?",
    "Une phrase qui dit ce que tu fais naturellement, mieux que la plupart des gens, et qui te donne de l'énergie.": "Una frase que diga lo que haces con naturalidad, mejor que la mayoría de la gente, y que te da energía.",
    "Une phrase trop longue pour un hexagone va dans le champ : raccourcis-la, puis ajoute-la.": "Una frase demasiado larga para un hexágono va al campo: acórtala y después añádela.",
    "Une piste à explorer": "Una pista por explorar",
    "Vente": "Ventas",
    "Vente : 2 sessions par semaine": "Ventas: 2 sesiones por semana",
    "Visualise ton talent comme un territoire, repère ce qui te met dans le flow et regarde tes compétences s'étendre.": "Visualiza tu talento como un territorio, descubre lo que te pone en flow y mira cómo se extienden tus competencias.",
    "Voici la carte de démonstration. Tu pourras créer la tienne depuis les Réglages.": "Este es el mapa de demostración. Podrás crear el tuyo desde los Ajustes.",
    "Voici ta carte ! Touche un hexagone pour l'ajuster ou le déplacer.": "¡Aquí tienes tu mapa! Toca un hexágono para ajustarlo o moverlo.",
    "Voir le suivi": "Ver el seguimiento",
    "Voir toute la carte": "Ver todo el mapa",
    "Voix et diction": "Voz y dicción",
    "Yoga": "Yoga",
    "Zone de flow": "Zona de flow",
    "Zone à déléguer": "Zona por delegar",
    "Zoomer": "Ampliar",
    "{a} et {b} ont échangé leur place.": "{a} y {b} han intercambiado su lugar.",
    "{fait} sur {cible} {quand}": "{fait} de {cible} {quand}",
    "{nom} : {n} session par {periode}": "{nom}: {n} sesión por {periode}",
    "{nom} : {n} sessions par {periode}": "{nom}: {n} sesiones por {periode}",
    "{nom} atteint {n} moments de flow : une proposition t'attend dans Progrès.": "{nom} alcanza {n} momentos de flow: te espera una propuesta en Progreso.",
    "{nom} attendra son heure. Il reste visible sur ta carte.": "{nom} esperará su momento. Sigue visible en tu mapa.",
    "{nom} devient une frontière : c'est là que tu grandis.": "{nom} se convierte en una frontera: ahí es donde creces.",
    "{nom} devient une frontière de ta carte.": "{nom} se convierte en una frontera de tu mapa.",
    "{nom} devient une île de flow, hors de ton talent principal.": "{nom} se convierte en una isla de flow, fuera de tu talento principal.",
    "{nom} fait partie de ton territoire natal.": "{nom} forma parte de tu territorio natal.",
    "{nom} rejoint la zone à déléguer. Tu peux le confier à d'autres.": "{nom} pasa a la zona por delegar. Puedes confiárselo a otras personas.",
    "{nom} rejoint tes territoires à conquérir.": "{nom} se une a tus territorios por conquistar.",
    "{nom} retrouve sa place automatique.": "{nom} recupera su lugar automático.",
    "{nom} élargit-il ton domaine d'action ?": "¿{nom} amplía tu campo de acción?",
    "{n} / {seuil} moments": "{n} / {seuil} momentos",
    "{n} proposition de conquête": "{n} propuesta de conquista",
    "{n} propositions de conquête": "{n} propuestas de conquista",
    "{n} suggestion écartée ne t'est plus proposée.": "{n} sugerencia descartada ya no se te propone.",
    "{n} suggestions écartées ne te sont plus proposées.": "{n} sugerencias descartadas ya no se te proponen.",
    "{province}, du côté de {region}": "{province}, por el lado de {region}",
    "« {nom} »": "«{nom}»",
    "« {nom} » compte {moments} de flow": "«{nom}» suma {moments} de flow",
    "À conquérir": "Por conquistar",
    "À déléguer": "Por delegar",
    "À l'aise": "Cómodo/a",
    "À quel point c'était exigeant ?": "¿Cuánta exigencia tuvo?",
    "À quel point tu te sentais à l'aise ?": "¿Cuán cómodo/a te sentías?",
    "À ranger": "Por colocar",
    "ça brille": "brilla",
    "Éclat : flow des 30 derniers jours": "Brillo: flow de los últimos 30 días",
    "Éclat : {niveau}": "Brillo: {niveau}",
    "Écouter pour aider": "Escuchar para ayudar",
    "Écrire des prompts": "Escribir prompts",
    "Écrire pour le web": "Escribir para la web",
    "Écriture créative": "Escritura creativa",
    "Écriture de sketchs": "Escritura de sketches",
    "Édition vidéo": "Edición de vídeo",
    "Éloigné": "Lejano",
    "Éloignée": "Lejana",
    "Énergie et humour": "Energía y humor",
    "Être dynamique": "Ser dinámico/a",
    "Être positif": "Ser positivo/a",
    "Être très ouvert": "Ser muy abierto/a",
    "Île": "Isla",
    "Île de flow": "Isla de flow",
    "Île {nom}": "Isla {nom}",
    "Île « {nom} », hors du talent principal": "Isla «{nom}», fuera del talento principal",
    "Îles de flow": "Islas de flow",
    "…afin de…": "…para…",
    "…dans un environnement où…": "…en un entorno donde…",
    "Même idée que « {nom} »": "Misma idea que «{nom}»",
    "Même univers que « {nom} » ({domaine})": "Mismo universo que «{nom}» ({domaine})",
    "Proche d'éléments de « {nom} »": "Cercano a elementos de «{nom}»",
    "Ne colle à aucune région : une île de flow": "No encaja en ninguna región: una isla de flow",
    "Analyse": "Análisis",
    "Nature": "Naturaleza",
    "Technique": "Técnica",
    "Ta carte à partir de ton résultat du quiz": "Tu mapa a partir del resultado de tu test",
    "Ton talent et tes sous-talents sont déjà proposés : la création guidée s'ouvre pré-remplie. Tu modifies tout ce que tu veux, puis tu crées ta carte.": "Tu talento y tus subtalentos ya están propuestos: la creación guiada se abre ya rellenada. Modificas lo que quieras y después creas tu mapa.",
    "Commencer avec mon résultat": "Empezar con mi resultado",
    "Depuis ton résultat du quiz": "Desde el resultado de tu test",
    "{n} idées pour t'inspirer, par domaine. Touche pour ajouter.": "{n} ideas para inspirarte, por ámbito. Toca para añadir.",
    "Voir moins": "Ver menos",
    "Voir plus ({n} idées de plus)": "Ver más ({n} ideas más)",
    "On a déjà rangé chaque élément dans la région la plus proche, avec la raison en petit. Garde ce qui te parle, déplace le reste.": "Ya hemos colocado cada elemento en la región más cercana, con el motivo en pequeño. Quédate con lo que te hable y mueve el resto.",
    "Ce qui ne colle à aucune région devient une île.": "Lo que no encaja en ninguna región se convierte en una isla.",
    "Sport et corps": "Deporte y cuerpo",
    "Art et scène": "Arte y escena",
    "Relationnel": "Relacional",
    "Analyse et réflexion": "Análisis y reflexión",
    "Technique et numérique": "Técnica y digital",
    "Natation": "Natación",
    "Vélo": "Ciclismo",
    "Musculation": "Musculación",
    "Randonnée": "Senderismo",
    "Pilates": "Pilates",
    "Sport d'équipe": "Deporte de equipo",
    "Coaching sportif": "Entrenamiento deportivo",
    "Théâtre": "Teatro",
    "Magie": "Magia",
    "Guitare": "Guitarra",
    "Piano": "Piano",
    "Percussions": "Percusión",
    "DJ et mix": "DJ y mezclas",
    "Arts du cirque": "Artes circenses",
    "Dessin": "Dibujo",
    "Peinture": "Pintura",
    "Illustration": "Ilustración",
    "Sculpture": "Escultura",
    "Céramique": "Cerámica",
    "Couture": "Costura",
    "Cuisine": "Cocina",
    "Pâtisserie": "Repostería",
    "Écriture de scénarios": "Escritura de guiones",
    "Poésie": "Poesía",
    "Écoute active": "Escucha activa",
    "Empathie": "Empatía",
    "Accompagnement individuel": "Acompañamiento individual",
    "Hospitalité": "Hospitalidad",
    "Bénévolat": "Voluntariado",
    "Travail en équipe": "Trabajo en equipo",
    "Donner du feedback": "Dar feedback",
    "Relation client": "Atención al cliente",
    "Tutorat": "Tutoría",
    "Vulgarisation": "Divulgación",
    "Enseigner aux enfants": "Enseñar a niños",
    "Concevoir un cours": "Diseñar un curso",
    "Recherche et documentation": "Investigación y documentación",
    "Synthèse": "Síntesis",
    "Veille": "Vigilancia del sector",
    "Résolution de problèmes": "Resolución de problemas",
    "Esprit critique": "Pensamiento crítico",
    "Statistiques": "Estadística",
    "Audit et diagnostic": "Auditoría y diagnóstico",
    "Stratégie": "Estrategia",
    "Modélisation": "Modelización",
    "Prise de décision": "Toma de decisiones",
    "Analyse financière": "Análisis financiero",
    "Planification": "Planificación",
    "Logistique": "Logística",
    "Priorisation": "Priorización",
    "Optimiser des processus": "Optimizar procesos",
    "Recrutement": "Selección de personal",
    "Déléguer": "Delegar",
    "Coordination d'équipe": "Coordinación de equipos",
    "Jardinage": "Jardinería",
    "Permaculture": "Permacultura",
    "Écologie et transition": "Ecología y transición",
    "Observation de la nature": "Observación de la naturaleza",
    "Apiculture": "Apicultura",
    "Cueillette et plantes": "Recolección y plantas",
    "Éducation à la nature": "Educación en la naturaleza",
    "Bricolage": "Bricolaje",
    "Menuiserie": "Carpintería",
    "Mécanique": "Mecánica",
    "Électronique": "Electrónica",
    "Réparation": "Reparación",
    "Programmation": "Programación",
    "Python": "Python",
    "Excel avancé": "Excel avanzado",
    "Référencement (SEO)": "Posicionamiento (SEO)",
    "Visualisation de données": "Visualización de datos",
    "Bases de données": "Bases de datos",
    "IA générative": "IA generativa",
    "Design d'interface (UX)": "Diseño de interfaces (UX)",
    "Chinois": "Chino",
    "Arabe": "Árabe",
    "Traduction": "Traducción",
    "Marketing": "Marketing",
    "Copywriting": "Copywriting",
    "Publicité en ligne": "Publicidad en línea",
    "Partenariats": "Alianzas",
    "E-commerce": "E-commerce",
    "Pitch et levée de fonds": "Pitch y captación de fondos",
    "Journalisme": "Periodismo",
    "Interviewer": "Entrevistar",
    "Rédiger des discours": "Redactar discursos",
    "Débat et argumentation": "Debate y argumentación",
    "Escape game": "Escape room",
    "Jeux de société": "Juegos de mesa",
    "Animer un quiz": "Dirigir un concurso de preguntas",
    "Animation pour enfants": "Animación infantil",
    "Bouger": "Moverse",
    "Se dépasser": "Superarse",
    "Entraîner": "Entrenar",
    "Prendre soin du corps": "Cuidar el cuerpo",
    "Jouer": "Jugar",
    "Émouvoir": "Emocionar",
    "Écouter": "Escuchar",
    "Réconcilier": "Reconciliar",
    "Créer": "Crear",
    "Imaginer": "Imaginar",
    "Inventer": "Inventar",
    "Embellir": "Embellecer",
    "Faire de ses mains": "Hacer cosas con las manos",
    "Analyser": "Analizar",
    "Comprendre": "Comprender",
    "Chercher": "Investigar",
    "Simplifier": "Simplificar",
    "Décider": "Decidir",
    "Organiser": "Organizar",
    "Coordonner": "Coordinar",
    "Structurer": "Estructurar",
    "Planifier": "Planificar",
    "Fiabiliser": "Hacer fiable",
    "Cultiver": "Cultivar",
    "Explorer la nature": "Explorar la naturaleza",
    "Protéger le vivant": "Proteger lo vivo",
    "Prendre l'air": "Tomar el aire",
    "Observer": "Observar",
    "Bricoler": "Trastear",
    "Réparer": "Reparar",
    "Automatiser": "Automatizar",
    "Construire": "Construir",
    "Programmer": "Programar",
    "Raconter": "Contar historias",
    "Convaincre": "Convencer",
    "Écrire": "Escribir",
    "Parler en public": "Hablar en público",
    "Faire connaître": "Dar a conocer",
    "Former": "Formar",
    "Accompagner": "Acompañar",
    "Vulgariser": "Divulgar",
    "Inspirer": "Inspirar",
    "Courir": "Correr",
    "Nager": "Nadar",
    "Faire du vélo": "Ir en bici",
    "Grimper": "Trepar",
    "Faire du yoga": "Hacer yoga",
    "Randonner": "Hacer senderismo",
    "Jouer en équipe": "Jugar en equipo",
    "Jouer de la musique": "Tocar música",
    "Faire de la magie": "Hacer magia",
    "Jouer la comédie": "Hacer teatro",
    "Faire rire un groupe": "Hacer reír a un grupo",
    "Écouter quelqu'un": "Escuchar a alguien",
    "Accueillir des gens": "Acoger a personas",
    "Aider à débloquer une situation": "Ayudar a desbloquear una situación",
    "Réconcilier deux personnes": "Reconciliar a dos personas",
    "Discuter pendant des heures": "Charlar durante horas",
    "Rencontrer des inconnus": "Conocer a desconocidos",
    "Dessiner": "Dibujar",
    "Peindre": "Pintar",
    "Cuisiner": "Cocinar",
    "Écrire un texte": "Escribir un texto",
    "Prendre des photos": "Hacer fotos",
    "Monter une vidéo": "Montar un vídeo",
    "Composer": "Componer",
    "Coudre ou fabriquer": "Coser o fabricar",
    "Imaginer un jeu": "Imaginar un juego",
    "Résoudre un problème complexe": "Resolver un problema complejo",
    "Analyser des chiffres": "Analizar cifras",
    "Faire une recherche approfondie": "Hacer una investigación a fondo",
    "Faire une synthèse": "Hacer una síntesis",
    "Comprendre un système": "Comprender un sistema",
    "Monter une stratégie": "Montar una estrategia",
    "Organiser un événement": "Organizar un evento",
    "Planifier un projet": "Planificar un proyecto",
    "Mettre de l'ordre": "Poner orden",
    "Coordonner une équipe": "Coordinar un equipo",
    "Optimiser un process": "Optimizar un proceso",
    "Préparer un voyage": "Preparar un viaje",
    "Jardiner": "Hacer jardinería",
    "Marcher en forêt": "Caminar por el bosque",
    "Observer les oiseaux": "Observar aves",
    "Camper": "Acampar",
    "Soigner des plantes": "Cuidar plantas",
    "Regarder les étoiles": "Mirar las estrellas",
    "Réparer un objet": "Reparar un objeto",
    "Automatiser une tâche": "Automatizar una tarea",
    "Construire quelque chose": "Construir algo",
    "Démonter pour comprendre": "Desmontar para comprender",
    "Prendre la parole en public": "Hablar en público",
    "Raconter une histoire": "Contar una historia",
    "Enregistrer un podcast": "Grabar un pódcast",
    "Rédiger un article": "Redactar un artículo",
    "Débattre": "Debatir",
    "Expliquer simplement": "Explicar con sencillez",
    "Former un groupe": "Formar a un grupo",
    "Préparer un cours": "Preparar una clase",
    "Mentorer quelqu'un": "Hacer de mentor/a de alguien",
    "Animer un séminaire": "Dirigir un seminario",
    "Faire découvrir une passion": "Dar a conocer una pasión",
    "Chant": "Canto",
    "Improvisation": "Improvisación",
    "Coaching": "Coaching",
    "Vente conseil": "Venta consultiva",
    "Découverte des besoins du client": "Descubrimiento de las necesidades del cliente",
    "Argumentaire de vente": "Argumentario de ventas",
    "Traiter les objections": "Tratar las objeciones",
    "Conclure une vente": "Cerrar una venta",
    "Rédiger un devis": "Redactar un presupuesto",
    "Mener un rendez-vous commercial": "Llevar una reunión comercial",
    "Vente par téléphone": "Venta telefónica",
    "Vendre en visioconférence": "Vender por videollamada",
    "Prospection par e-mail": "Prospección por correo electrónico",
    "Social selling": "Social selling",
    "Suivi commercial (CRM)": "Seguimiento comercial (CRM)",
    "Fidélisation client": "Fidelización de clientes",
    "Vente additionnelle": "Venta adicional",
    "Démonstration de produit": "Demostración de producto",
    "Vente aux entreprises (B2B)": "Venta a empresas (B2B)",
    "Répondre à un appel d'offres": "Responder a una licitación",
    "Relance commerciale": "Seguimiento comercial de clientes potenciales",
    "Vendre sur un salon": "Vender en una feria",
    "Obtenir des recommandations": "Conseguir recomendaciones",
    "Vendre ses services d'indépendant": "Vender tus servicios como autónomo",
    "Animer un groupe": "Dirigir un grupo",
    "Mise en page": "Maquetación",
    "Retouche photo": "Retoque fotográfico",
    "Création de visuels": "Creación de imágenes",
    "Ménage et rangement": "Limpieza y orden",
    "Répondre aux e-mails": "Responder a correos electrónicos",
    "Service après-vente": "Servicio posventa",
    "Gestion des réclamations": "Gestión de reclamaciones",
    "Prise de contact à froid": "Primer contacto en frío",
    "Prospection à froid": "Prospección en frío",
    "Relances commerciales": "Seguimientos comerciales",
    "Rédaction des devis": "Redacción de presupuestos",
    "Saisie de données": "Introducción de datos",
    "Tableaux de bord et reporting": "Cuadros de mando e informes",
    "Recherche documentaire": "Búsqueda documental",
    "Préparation du matériel de formation": "Preparación del material de formación",
    "Inscriptions et convocations": "Inscripciones y convocatorias",
    "Vente et business": "Ventas y negocios",
    "Formateur·rice": "Formador/a",
    "Coach professionnel·le": "Coach profesional",
    "Facilitateur·rice d'ateliers": "Facilitador/a de talleres",
    "Médiateur·rice": "Mediador/a",
    "Consultant·e RH": "Consultor/a de RR. HH.",
    "Éducateur·rice spécialisé·e": "Educador/a especializado/a",
    "Enseignant·e du primaire": "Maestro/a de primaria",
    "Professeur·e de langues": "Profesor/a de idiomas",
    "Animateur·rice pour enfants": "Monitor/a infantil",
    "Manager d'équipe": "Jefe/a de equipo",
    "Chef·fe de projet": "Jefe/a de proyecto",
    "Organisateur·rice d'événements": "Organizador/a de eventos",
    "Assistant·e de direction": "Asistente de dirección",
    "Comptable": "Contable",
    "Analyste financier·ère": "Analista financiero/a",
    "Auditeur·rice qualité": "Auditor/a de calidad",
    "Consultant·e en stratégie": "Consultor/a de estrategia",
    "Chargé·e d'études": "Responsable de estudios",
    "Chargé·e de recrutement": "Responsable de selección",
    "Hôte·sse d'accueil": "Recepcionista",
    "Commercial·e B2B": "Comercial B2B",
    "Business developer": "Business developer",
    "Responsable relation client": "Responsable de atención al cliente",
    "Responsable des partenariats": "Responsable de alianzas",
    "Responsable marketing": "Responsable de marketing",
    "E-commerçant·e": "Comerciante online",
    "Chargé·e de communication": "Responsable de comunicación",
    "Community manager": "Community manager",
    "Rédacteur·rice web": "Redactor/a web",
    "Journaliste": "Periodista",
    "Traducteur·rice": "Traductor/a",
    "Vidéaste": "Videógrafo/a",
    "Graphiste": "Diseñador/a gráfico/a",
    "Illustrateur·rice": "Ilustrador/a",
    "Photographe": "Fotógrafo/a",
    "UX designer": "Diseñador/a UX",
    "Auteur·rice": "Autor/a",
    "Scénariste": "Guionista",
    "Développeur·se": "Desarrollador/a",
    "Spécialiste no-code": "Especialista no-code",
    "Analyste de données": "Analista de datos",
    "Consultant·e en intelligence artificielle": "Consultor/a de inteligencia artificial",
    "Comédien·ne": "Actor/Actriz",
    "Humoriste": "Humorista",
    "Musicien·ne intervenant·e": "Músico/a educador/a",
    "Artiste de cirque": "Artista de circo",
    "Professeur·e de yoga": "Profesor/a de yoga",
    "Coach sportif·ve": "Entrenador/a deportivo/a",
    "Professeur·e de danse": "Profesor/a de baile",
    "Guide nature": "Guía de naturaleza",
    "Permaculteur·rice": "Permacultor/a",
    "Chargé·e de transition écologique": "Responsable de transición ecológica",
    "Cuisinier·ère traiteur": "Cocinero/a de catering",
    "Menuisier·ère": "Carpintero/a",
    "Chargé·e de projets associatifs": "Responsable de proyectos asociativos",
    "Conférencier·ère": "Conferenciante",
    "Maître·sse de cérémonie": "Maestro/a de ceremonias",
    "Créateur·rice de contenus": "Creador/a de contenidos",
    "Créateur·rice de podcast": "Creador/a de pódcast",
    "Mentor bénévole": "Mentor/a voluntario/a",
    "Organisateur·rice de rencontres": "Organizador/a de encuentros",
    "Troupe d'improvisation": "Compañía de improvisación",
    "Créateur·rice d'escape games": "Creador/a de escape rooms",
    "Cours collectifs de sport ou de danse": "Clases colectivas de deporte o de baile",
    "Chorale ou groupe de musique": "Coro o grupo de música",
    "Jardin partagé": "Huerto compartido",
    "Repair café": "Repair café",
    "Scène ouverte et poésie": "Escenario abierto y poesía",
    "Magicien·ne d'animation": "Mago/a de animación",
    "Ateliers de cohésion d'équipe": "Talleres de cohesión de equipo",
    "Programme d'accompagnement individuel": "Programa de acompañamiento individual",
    "Formation en ligne": "Formación en línea",
    "Retraite ou séjour thématique": "Retiro o estancia temática",
    "Communauté en ligne sur abonnement": "Comunidad en línea por suscripción",
    "Newsletter d'expert·e": "Boletín de experto/a",
    "Ateliers pour enfants et familles": "Talleres para niños y familias",
    "Conférences et ateliers en entreprise": "Conferencias y talleres en empresas",
    "Assistance à distance pour indépendants": "Asistencia a distancia para autónomos",
    "Stages et balades nature": "Cursos y paseos por la naturaleza",
    "Boutique de créations": "Tienda de creaciones",
    "Audit flash pour petites entreprises": "Auditoría exprés para pequeñas empresas",
    "Coaching de prise de parole": "Coaching para hablar en público",
    "Ateliers de cuisine": "Talleres de cocina",
    "« {piste} » est visée : tu as déjà tout ce qu'il faut.": "«{piste}» es tu objetivo: ya tienes todo lo necesario.",
    "Piste retirée. Tes territoires en conquête restent sur la carte.": "Pista retirada. Tus territorios en conquista se quedan en el mapa.",
    "Ce PDF ne contient pas de résultat du quiz. Télécharge-le à nouveau depuis le quiz Talent Unique.": "Este PDF no contiene ningún resultado del test. Descárgalo de nuevo desde el test de Talento Único.",
    "{n} territoire en conquête pour « {piste} » : tu les classes par priorité.": "{n} territorio en conquista para «{piste}»: los clasificas por prioridad.",
    "{n} territoires en conquête pour « {piste} » : tu les classes par priorité.": "{n} territorios en conquista para «{piste}»: los clasificas por prioridad.",
    "Métier": "Profesión",
    "Activité": "Actividad",
    "Offre indépendante": "Oferta de autónomo",
    "Ressourcement": "Recarga de energía",
    "Zone de ressourcement": "Zona de recarga",
    "Importer mon résultat QCM (PDF)": "Importar mi resultado del test (PDF)",
    "Ce qui te recharge": "Lo que te recarga",
    "Ces idées forment ta zone de ressourcement, à l'écart de ta carte. C'est facultatif.": "Estas ideas forman tu zona de recarga, apartada de tu mapa. Es opcional.",
    "Ex. : Marcher en forêt": "Ej.: Caminar por el bosque",
    "Pour la piste : {pistes}": "Para la pista: {pistes}",
    "Voir toutes les compétences": "Ver todas las competencias",
    "Correspondance : {n} %": "Coincidencia: {n} %",
    "Ce qui la justifie": "Lo que la justifica",
    "Pas encore d'hexagone sur ta carte : c'est une piste à explorer.": "Todavía no hay ningún hexágono en tu mapa: es una pista por explorar.",
    "Compétences manquantes": "Competencias que faltan",
    "Rien ne manque : tu as déjà tout ce qu'il faut pour cette piste.": "No falta nada: ya tienes todo lo necesario para esta pista.",
    "Piste visée": "Pista elegida",
    "Ne plus viser": "Dejar de apuntar a ella",
    "Viser cette piste": "Apuntar a esta pista",
    "Mes priorités": "Mis prioridades",
    "Le n°1 est le territoire que tu attaques d'abord. Change l'ordre avec les flèches : il est enregistré.": "El n.º 1 es el territorio que atacas primero. Cambia el orden con las flechas: se guarda.",
    "pour : {pistes}": "para: {pistes}",
    "Mes pistes": "Mis pistas",
    "Des pistes qui collent à ton talent": "Pistas que encajan con tu talento",
    "Calculé sur ta carte : tes territoires, tes régions et tes moments de flow. Une piste est une idée à explorer, pas un verdict.": "Calculado sobre tu mapa: tus territorios, tus regiones y tus momentos de flow. Una pista es una idea por explorar, no un veredicto.",
    "Pas encore sur ta carte": "Todavía no está en tu mapa",
    "{n} sur {total} sur ta carte": "{n} de {total} en tu mapa",
    "Touche un hexagone pour le conquérir ou le voir sur ta carte.": "Toca un hexágono para conquistarlo o verlo en tu mapa.",
    "J'y vais : en conquête": "Voy a por ello: en conquista",
    "À conquérir plus tard": "Por conquistar más adelante",
    "Voir sur ma carte": "Ver en mi mapa",
    "Toutes les compétences": "Todas las competencias",
    "Tout ce que tu peux explorer": "Todo lo que puedes explorar",
    "La bibliothèque entière, par domaine. Tu peux conquérir n'importe quel hexagone, pas seulement ceux que ta carte te propose.": "Toda la biblioteca, por ámbito. Puedes conquistar cualquier hexágono, no solo los que te propone tu mapa.",
    "Mes pistes : métiers et activités qui collent à mon talent": "Mis pistas: profesiones y actividades que encajan con mi talento",
    "Facturation": "Facturación",
    "Relances de paiement": "Reclamación de pagos",
    "Agenda et prises de rendez-vous": "Agenda y citas",
    "Classement des documents": "Archivo de documentos",
    "Notes de frais": "Notas de gastos",
    "Déclarations et paperasse": "Declaraciones y papeleo",
    "Réservations de voyages et de salles": "Reservas de viajes y de salas",
    "Logistique et envois de colis": "Logística y envío de paquetes",
    "Mise à jour du site web": "Actualización del sitio web",
    "Support informatique": "Soporte informático",
    "Sauvegardes et mises à jour": "Copias de seguridad y actualizaciones",
    "Paramétrage des outils": "Configuración de herramientas",
    "Réparations et petits travaux": "Reparaciones y pequeñas obras",
    "Relecture et correction": "Revisión y corrección",
    "Gestion des réseaux sociaux": "Gestión de redes sociales",
    "Envoi de la newsletter": "Envío del boletín",
    "Transcription d'enregistrements": "Transcripción de grabaciones"
  };
})(globalThis.CarteTalent = globalThis.CarteTalent || {});
