// Mon espace : textes en français seulement. Copie du cahier des charges (E.6).

export const IMPORT_ACTIF = false; // PR 2 : passer à true

export const ESPACE = {
  meta: { titre: "Mon espace" },
  entete: { nom: "Mon espace", compte: "Mon compte", coach: "Espace coach" },
  bonjour: (prenom: string) => (prenom ? `Bonjour ${prenom}` : "Bonjour"),
  intro: "Tous tes outils Magic Humans au même endroit. Tu cliques, c'est parti.",
  sections: { pro: "Côté pro", coeur: "Côté cœur" },
  fiche: {
    videTitre: "Tu as déjà fait ton accompagnement Talent Unique ?",
    videTexte: "Dépose ta fiche (page Notion, Word ou PDF). Tes outils se remplissent tout seuls, sans refaire le quiz.",
    videBouton: "Déposer ma fiche",
    pasDeFiche: "Pas encore de fiche ?",
    lienQuiz: "Fais le quiz Talent Unique en 6 minutes",
    surtitre: "Ton Talent Unique",
    voir: "Voir ma fiche",
    modifier: "Modifier",
    bientot: "Bientôt ici : dépose ta fiche Talent Unique et tes outils se rempliront tout seuls.",
  },
  notices: {
    ficheOk: "C'est enregistré. Tes outils sont prêts.",
    ficheSupprimee: "Ta fiche est supprimée.",
  },
  appel: {
    texte: "Envie d'en parler ?",
    detail: "Appel Découverte, 1\u00a0heure, offert.",
    bouton: "En parler avec Pierre",
  },
  connexion: {
    titre: "Ton espace Magic Humans",
    texte: "Connecte-toi pour retrouver tous tes outils. Pas encore de compte ? Tu le crées en une minute.",
    creer: "Créer mon compte",
    connecter: "Me connecter",
  },
  importer: {
    titre: "Dépose ta fiche Talent Unique",
    intro: "Celle que tu as reçue après ton accompagnement avec Pierre. Ton fichier reste sur ton appareil : seules les infos que tu valides sont gardées dans ton espace.",
    coller: { titre: "Coller ma page Notion", texte: "Ouvre ta page, sélectionne tout, copie, puis colle ici.", zone: "Colle ta page ici", bouton: "Lire ma fiche" },
    fichier: { titre: "Déposer un fichier", texte: "Word, PDF ou export Notion (.docx, .pdf, .md, .html, .zip).", bouton: "Choisir mon fichier", glisser: "ou glisse-le ici" },
    main: { titre: "Remplir à la main", texte: "Tu as ta fiche sous les yeux ? Recopie l'essentiel en 5 minutes." },
    aide: {
      titre: "Comment récupérer ma page Notion ?",
      etapes: [
        "Ouvre ta page Talent Unique dans Notion et déplie tous les blocs repliés (les petites flèches).",
        "Sur ordinateur : clique dans la page, fais Ctrl + A deux fois (Cmd + A sur Mac), puis Ctrl + C. Reviens ici et colle avec Ctrl + V.",
        "Autre solution : menu ••• en haut à droite, Exporter, choisis Markdown ou HTML, puis dépose le fichier ici.",
        "Tu n'as pas accès à ta page ? Demande-la à Pierre, il te l'envoie.",
      ],
    },
    lecture: "Je lis ta fiche…",
    erreurs: {
      formatInconnu: "Je ne sais pas lire ce type de fichier. Essaie Word, PDF ou un export Notion.",
      tropGros: "Ce fichier est trop lourd (10 Mo au plus).",
      vide: "Je n'ai trouvé aucun texte dans ce document. Si c'est un scan, colle plutôt le texte, ou remplis à la main.",
      lecture: "Je n'ai pas réussi à ouvrir ce fichier. Essaie de coller le texte à la place.",
    },
  },
  verification: {
    titre: "Vérifie ta fiche",
    intro: "Voici ce que j'ai trouvé. Corrige ce qui ne te ressemble pas, puis enregistre.",
    luOk: "J'ai reconnu ta fiche Talent Unique. Jette un œil, puis enregistre.",
    luPartiel: "Je n'ai pas tout reconnu. Pas grave : complète les cases marquées « à compléter », ça prend 5 minutes.",
    badges: { trouve: "trouvé dans ta fiche", deduit: "à vérifier", manque: "à compléter" },
    groupes: { essentiel: "L'essentiel", outils: "Pour tes outils", reste: "Le reste de ta fiche" },
    uneParLigne: "Une idée par ligne",
    champs: {
      titre: "Le titre de ton talent",
      mecanisme: "Ton talent en une phrase",
      mecanismeAide: "Ce que tu fais naturellement, mieux que personne.",
      contexte: "Ton contexte déclencheur",
      contexteAide: "Là où ton talent s'allume.",
      benefice: "Ce que ton talent apporte aux autres",
      antiContexte: "Ce qui éteint ton talent",
      valeurs: "Tes valeurs, de la plus importante à la moins importante",
      reussite: "Là où ton talent est une force",
      echec: "Là où il devient un défaut",
      qualites: "Tes qualités",
      defauts: "Le revers de tes qualités",
      aimeQuand: "J'aime quand…",
      metiersParfaits: "Les métiers faits pour toi",
      offres: "Tes offres possibles en indépendant",
      avatars: "Tes clients idéaux",
      avatarProfil: "Qui c'est",
      avatarBesoins: "Ce dont il a besoin",
      avatarApport: "Ce que tu lui apportes",
      autresTitres: "Autres titres possibles",
      resume: "Ton talent en quelques phrases",
      paradoxe: "Ton plus grand talent, ton plus grand défaut",
      antiValeurs: "Tes anti-valeurs",
      enneagrammeBase: "Ta base dans l'ennéagramme",
      enneagrammeSousType: "Ton sous-type",
      managerIdeal: "Ton manager ou client idéal",
      contraintes: "Tes autres contraintes",
      conseils: "Les conseils pour bien l'utiliser",
      talonAchille: "Ton talon d'Achille",
      sousPression: "Quand on t'empêche d'exprimer ton talent",
      vigilance: "Tes points de vigilance",
      axes: "Tes axes de progrès",
      etapes: "Les étapes de ton talent",
      metiersTres: "Les métiers très compatibles",
      metiersCondition: "Les métiers possibles avec quelques compétences en plus",
      secteurs: "Les secteurs à privilégier",
      questions: "Les questions à poser en entretien",
      prochainesEtapes: "Tes prochaines étapes",
    },
    erreurs: { requis: "Cette case est nécessaire pour tes outils.", tropCourt: "Un peu plus de détails, s'il te plaît (12 caractères au moins)." },
    consentement: "J'accepte que Magic Humans garde ces informations dans mon espace pour faire marcher mes outils. Je peux les modifier ou les supprimer quand je veux.",
    enSavoirPlus: "En savoir plus",
    enregistrer: "Enregistrer ma fiche",
    annuler: "Revenir à mon espace",
    erreurEnregistrement: "Oups, l'enregistrement n'a pas marché. Réessaie dans un instant.",
  },
  pageFiche: {
    titre: "Ma fiche Talent Unique",
    modifier: "Modifier",
    supprimer: "Supprimer ma fiche",
    confirmer: "Ta fiche sera effacée de ton espace. Les Boussoles déjà créées restent là. On supprime ?",
    oui: "Oui, supprimer",
    non: "Non, je la garde",
  },
  compte: {
    titre: "Supprimer mon compte",
    texte: "Ton compte, ta fiche et toutes tes Boussoles seront effacés pour de bon. Écris SUPPRIMER pour confirmer.",
    bouton: "Supprimer mon compte",
    motAttendu: "Écris SUPPRIMER en majuscules.",
    compteCoach: "Un compte coach ne se supprime pas d'ici.",
  },
  outilsAvecFiche: { // PR 3
    boussole: "Créer ma Boussole avec ma fiche",
    mesBoussoles: "Ouvrir mes Boussoles",
    cibleur: "Trouver mes clients avec ma fiche",
    carte: "Dessiner ma carte avec ma fiche",
    pret: "Déjà rempli avec ta fiche",
  },
} as const;
